use egglog_ast::generic_ast::GenericExpr;
use std::fmt::{Display, Formatter};
use std::hash::Hash;
use std::hash::Hasher;

use crate::ast::CorrespondingVar;
use crate::core::ResolvedCall;
use crate::typechecking::FunctionRegistrationId;
use crate::{ArcSort, sort};

/// Deterministic identity of one resolved lexical binding.
///
/// The ordinal is allocated from the owning frontend's [`SymbolGen`](crate::util::SymbolGen)
/// high-water mark. It is semantic authority within that resolved command
/// stream; the variable's spelling remains diagnostic only.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ResolvedBindingId(u32);

impl ResolvedBindingId {
    pub(crate) const fn new(ordinal: u32) -> Self {
        Self(ordinal)
    }

    /// The deterministic allocation ordinal within the owning frontend stream.
    pub const fn ordinal(self) -> u32 {
        self.0
    }
}

/// The exact binding authority carried by a resolved variable.
///
/// Display names remain useful for diagnostics and for the ordinary lexical
/// environment, but merge consumers must use the structured variants below.
/// In particular, no downstream pass should recover an old/new column or a
/// merge-local slot from a spelling such as `old`, `new1`, or a `let` name.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ResolvedVarBinding {
    /// An ordinary lexical variable in a rule, action block, or generated IR.
    Lexical { id: ResolvedBindingId },
    /// A global binding/reference that will lower to this exact nullary
    /// function during global removal.
    Global { function: FunctionRegistrationId },
    /// The owning merge row's existing value column.
    MergeOld { column: usize },
    /// The candidate merge row's value column.
    MergeNew { column: usize },
    /// A merge action block's exact source-order `let` slot.
    MergeLet { slot: usize },
}

#[derive(Debug, Clone)]
pub struct ResolvedVar {
    pub name: String,
    pub sort: ArcSort,
    pub binding: ResolvedVarBinding,
    /// Is this a reference to a global variable?
    /// After the `remove_globals` pass, this should be `false`.
    ///
    /// NB: we distinguish between a global reference and a global binding.
    /// The current implementation of `Eq` and `Hash` does not take this field
    /// into consideration.
    /// Overall, the definition of equality between two ResolvedVars is dicey.
    pub is_global_ref: bool,
}

impl PartialEq for ResolvedVar {
    fn eq(&self, other: &Self) -> bool {
        self.binding == other.binding
    }
}

impl Eq for ResolvedVar {}

impl Hash for ResolvedVar {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.binding.hash(state);
    }
}

impl Display for ResolvedVar {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name)
    }
}

pub type Expr = GenericExpr<String, String>;
/// A generated expression is an expression that is generated by the system
/// and does not have annotations.
pub type ResolvedExpr = GenericExpr<ResolvedCall, ResolvedVar>;
/// A [`MappedExpr`] arises naturally when you want a mapping between an expression
/// and its flattened form. It records this mapping by annotating each `Head`
/// with a `Leaf`, which it maps to in the flattened form.
/// A useful operation on `MappedExpr`s is
/// [`MappedExprExt::get_corresponding_var_or_lit`](crate::ast::MappedExprExt::get_corresponding_var_or_lit).
pub(crate) type MappedExpr<Head, Leaf> = GenericExpr<CorrespondingVar<Head, Leaf>, Leaf>;

pub(crate) trait ResolvedExprExt {
    fn output_type(&self) -> ArcSort;
    fn get_global_var(&self) -> Option<ResolvedVar>;
}

impl ResolvedExprExt for ResolvedExpr {
    fn output_type(&self) -> ArcSort {
        match self {
            ResolvedExpr::Lit(_, lit) => sort::literal_sort(lit),
            ResolvedExpr::Var(_, resolved_var) => resolved_var.sort.clone(),
            ResolvedExpr::Call(_, resolved_call, _) => resolved_call.output().clone(),
        }
    }

    fn get_global_var(&self) -> Option<ResolvedVar> {
        match self {
            // Exact nominal authority decides semantics. `is_global_ref` is
            // retained only as legacy diagnostic metadata and may not turn a
            // lexical binding into a global (or hide an exact global).
            ResolvedExpr::Var(_, v) if matches!(v.binding, ResolvedVarBinding::Global { .. }) => {
                Some(v.clone())
            }
            _ => None,
        }
    }
}

#[macro_export]
macro_rules! call {
    ($func:expr, $args:expr) => {
        $crate::ast::GenericExpr::Call($crate::span!(), $func.into(), $args.into_iter().collect())
    };
}

#[macro_export]
macro_rules! lit {
    ($lit:expr) => {
        $crate::ast::GenericExpr::Lit($crate::span!(), $lit.into())
    };
}

#[macro_export]
macro_rules! var {
    ($var:expr) => {
        $crate::ast::GenericExpr::Var($crate::span!(), $var.into())
    };
}

// Rust macro annoyance; see stackoverflow.com/questions/26731243/how-do-i-use-a-macro-across-module-files
pub use {call, lit, var};
