[package]
name = "egglog-experimental"
version = "3.0.0"
edition = "2024"
description = "Experimental extensions to the egglog language."
repository = "https://github.com/egraphs-good/egglog-experimental"
keywords = ["e-graphs", "egglog", "datalog", "compiler", "equality"]
license = "MIT"
readme = "README.md"

[[test]]
harness = false
name = "files"

[features]
default = ["bin"]
bin = ["egglog/bin"]

[dependencies]
egglog = { version = "3.0.0", git = "https://github.com/egraphs-good/egglog.git", rev = "90635860397ce710f8c0a4eeb04154a8ebc3ac05", default-features = false }
egglog-ast = { version = "3.0.0", git = "https://github.com/egraphs-good/egglog.git", rev = "90635860397ce710f8c0a4eeb04154a8ebc3ac05", default-features = false }
egglog-reports = { version = "3.0.0", git = "https://github.com/egraphs-good/egglog.git", rev = "90635860397ce710f8c0a4eeb04154a8ebc3ac05", default-features = false }

num = "0.4.3"
lazy_static = "1.4"
log = "0.4"
stacker = "0.1.25"
fixedbitset = "0.5.7"
# Greedy-DAG's hot maps were 1.90% faster than std on the Taylor 51 canary.
hashbrown = "0.16.0"

[dev-dependencies]
glob = "0.3.1"
libtest-mimic = "0.8.1"
