#!/usr/bin/env python3
"""Compile the reference `sdql` rewrite rules into the slotted encoding.

The rules are `slotted/languages/sdql.egg`, written in the slotted language and read from
there rather than restated here; the recipe that compiles them is
`slotted/slotted-encoder.py`, which `slotted/tests/user-rules.egg`
documents.  What `sdql` adds over the differential harness's two-child `App2`/`App3`
atoms is the per-language constructors of `slotted/languages/sdql.egg`,
which have one to six children and payload columns, and with them four cases the
harness's corpus does not reach:

  * a PAYLOAD LEAF in a child position -- `0`, `mult`.  Its row is never deleted
    or migrated, so it is a stable handle, but its class's canonical value need
    not be that row, so the atom joins `(RenamesToLeader (Num 0) _ C)` and uses
    `C` for the child rather than writing the leaf into the column;
  * a BUILT BINDER node.  Its slots are its edges' images MINUS what it binds,
    or the parent's edge to it names slots the child's class does not have;
  * an RHS slot the LHS never pinned -- `get-to-sum`'s `$k`, `$v`.  One
    `find-mapping-total` over a domain of that size mints them, avoiding every
    slot the pattern named;
  * an arity other than two, everywhere.

Atoms are compiled in pre-order from the LHS root, which is already the
connectivity the recipe requires.  `connected_order`'s further preference -- a
binder is not the atom that fixes slots(pattern) -- is not followed: most `sdql`
rules are rooted at a binder, and taking the root first pins each bound slot off
its own edge instead of minting a name for it.  M7 in
`slotted/tests/user-rules.egg` is the same shape.

Terms in the table below:

    "?x"            a pattern variable
    "$x"            a slot literal -- a binder column, or the reference's
                    `(var $x)` in an ordinary child column.  Both are the class
                    `(Var 0)` reached by an edge `0 -> $x`
    ("Op", ...)     a node; payload columns take Python literals, so `("Num", 0)`
                    and `("Symbol", "mult")` are the reference's `0` and `mult`

    python3 slotted/gen-sdql-rules.py
"""

import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
enc = __import__("slotted-encoder")
sc = __import__("slotted-egglog")


OUT = pathlib.Path(os.environ.get("SDQL_OUT", "target/slotted/slotted-sdql-rules.egg"))

# Re-introducible bugs, so the checks in `slotted/tests/sdql-rewrites.egg` can be
# shown to test what they were written for.  The encoder's flags, under the same
# names `XDIFF_BUGS` takes in `slotted/xdiff/xdiff.py`.
#   SDQL_BUGS=slot-late   a slot literal checked after the renaming, not with it
#   SDQL_BUGS=root-only   an atom's renaming solved from its root alone
#   SDQL_BUGS=wide-kids   a variable used at the matched node's slots, not its class's
#   SDQL_BUGS=no-guard    the slot side conditions dropped
# Set SDQL_OUT to keep a mutant out of the tree.
BUGS = {b for b in os.environ.get("SDQL_BUGS", "").split(",") if b}


# ------------------------------------------------------------------- the rules
# `(name, lhs, rhs)`, optionally `conds` and `fresh`.  Each `conds` entry is
# `(slot, pvar)` reading "that slot is not among the variable's slots", the
# reference's `!subst[v].slots().contains(&Slot::named(s))`.  `fresh` names RHS
# slots the LHS never pinned, which have to be minted.
#
# Ported from `sdql_rules()` in `slotted-egraphs/benches/sdql.rs`, minus `beta`.


HEADER = """\
;;; GENERATED by slotted/gen-sdql-rules.py -- do not edit.
;;;
;;; The reference `sdql` rewrite rules -- `sdql_rules()` in
;;; `slotted-egraphs/benches/sdql.rs` -- compiled into the slotted encoding by the
;;; recipe in `slotted/tests/user-rules.egg`.
;;;
;;; The rules themselves are `slotted/languages/sdql.egg`, written in the slotted language;
;;; read them there. This file is what they compile to.
;;;
;;; `beta` is NOT here: it substitutes, which needs `slotted-subst` and frame
;;; plumbing rather than this compiler.  The other 43 are.
;;;
;;; These are USER rules, so they go in their own ruleset and the machinery is
;;; saturated between finite steps of them:
;;;
;;;     (run-schedule (saturate (run slotted))
;;;                   (repeat N (seq (run sdql 1) (saturate (run slotted)))))
;;;
;;; `slotted/tests/sdql-rewrites.egg` is what checks them -- written in the slotted
;;; language over the same rules, and compiled at test time.

(include "target/slotted/slotted-lang-sdql.egg")

(ruleset sdql)
"""


# ---------------------------------------------------------------- the compiler
#: The rules, in the slotted language. One source for both this file and
#: `slotted-egglog.py`, so the .egg tests and the differential harness cannot be
#: running different rules from each other.
SOURCE = pathlib.Path("slotted/languages/sdql.egg")


def main():
    src = sc.Source(SOURCE)
    out = [HEADER]
    n = 0
    for form in sc.parse(SOURCE.read_text()):
        if not (isinstance(form, list) and form and form[0] == "rewrite"):
            continue
        name = sc.rule_name(src, form)
        assert name, f"a rewrite with no :name in {SOURCE}: {form[1]}"
        out.append(
            f"\n;; {name}\n" + sc.compile_rewrite(src, form, tail=f'\n      :ruleset sdql :name "{name}")', bugs=BUGS)
        )
        n += 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT} ({n} rules)")


if __name__ == "__main__":
    main()
