//! Stable identities and passive records in a captured execution trace.
//!
//! Trace identities use compact integer newtypes generated by the local
//! `trace_handle!` macro. They are distinct types because mixing a fact,
//! firing, execution wave, and history position would be a semantic error.
//! Unlike ids made by the crate's `define_id!`, several trace handles are
//! one-based sentinels, temporal coordinates, or prefix counts rather than
//! dense zero-based collection indexes; deliberately omitting `NumericId`
//! prevents accidental `usize` indexing and truncation of `u64` history.

use super::*;

macro_rules! trace_handle {
    ($(#[$meta:meta])* $visibility:vis $name:ident, $inner:ty) => {
        $(#[$meta])*
        #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
        $visibility struct $name($inner);

        impl $name {
            /// Creates a handle from its compact trace-local integer representation.
            $visibility const fn new(value: $inner) -> Self {
                Self(value)
            }

            /// Returns the compact trace-local integer representation.
            $visibility const fn get(self) -> $inner {
                self.0
            }
        }
    };
}

trace_handle!(
    /// Stable identity of one immutable effective logical-row occurrence.
    pub FactId,
    u64
);
trace_handle!(
    /// Stable identity of one effective grounded rule match whose effects share a cause.
    pub FiringId,
    u64
);
trace_handle!(
    /// Stable node identity in the typed structural replay-term DAG.
    pub ReplayTermId,
    u32
);
trace_handle!(
    /// Frontend-assigned identity of a logical sort used to type replay terms and endpoints.
    pub ReplaySortId,
    u32
);
trace_handle!(
    /// Frontend-assigned identity of a structural operation or constructor.
    pub ReplayOpId,
    u32
);
trace_handle!(
    /// Dense one-based identity of an effective native union edge, including alias joins.
    pub AppliedEqualityId,
    u64
);
trace_handle!(
    /// Synchronous execution or rebuild wave whose effects share a pre-wave state.
    ///
    /// A wave groups concurrent semantics; it does not totally order events within or across streams.
    pub Wave,
    u64
);
trace_handle!(
    /// Cross-stream mutation/check ordinal or an inclusive sampled history cutoff.
    ///
    /// Facts, applied equalities, rekeys, removals, and checks receive unique
    /// positions. Firings do not: all lanes in one observed batch carry the
    /// current inclusive high-water mark. It also determines the visible
    /// applied-equality prefix and bounds row lifetimes; zero is the boundary
    /// before all retained events.
    pub HistoryPosition,
    u64
);
trace_handle!(
    /// Identity of a static recipe that reconstructs all replay-typed cells of a row.
    pub RowOriginSiteId,
    u32
);
trace_handle!(
    /// Identity of a static recipe that reconstructs one structural replay term.
    pub(crate) TermOriginSiteId,
    u32
);
trace_handle!(
    /// Capture-time identity of a non-rule cause before publication.
    pub CauseDraftId,
    u64
);
trace_handle!(
    /// Stable published identity of a shared non-rule cause node.
    pub CauseId,
    u32
);

/// Replay-observable keyed-table semantics.
///
/// Constructor and value-function removals can change a later grounded write
/// or lookup-or-insert. Presence relations have no merge-bearing cell, so
/// their removals are not retained.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ReplayTableKind {
    /// Set-like table whose removals cannot affect a later merge-bearing value.
    PresenceRelation,
    /// Interning table whose key denotes the constructor result in its value column.
    Constructor,
    /// Keyed function whose merge-bearing value can affect later grounded operations.
    ValueFunction,
}

/// Stable index into the shared causal DAG.
/// A dependency can point directly at an observed firing or at a shared
/// non-rule cause node. Keeping the tagged distinction public avoids
/// manufacturing one cause-arena node for every native firing.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum CauseRef {
    /// The observed rule match directly caused the event.
    Rule(
        /// Identity of the causing firing.
        FiringId,
    ),
    /// A shared source, merge, rebuild, or container-maintenance node caused the event.
    Cause(
        /// Identity of the causing non-rule node.
        CauseId,
    ),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct PremiseSlot(u16);

impl PremiseSlot {
    pub(crate) fn from_usize(value: usize) -> Self {
        Self(
            value
                .try_into()
                .expect("a capture has more than u16 premises"),
        )
    }

    pub(crate) fn index(self) -> usize {
        self.0 as usize
    }
}

impl FactId {
    pub(crate) const MISSING: Self = Self(0);

    pub(crate) fn is_missing(self) -> bool {
        self == Self::MISSING
    }
}

impl ReplayTermId {
    /// Sentinel indicating that a raw historical endpoint has not projected structural syntax.
    pub const MISSING: Self = Self(0);

    /// Returns whether this id is the missing-term sentinel.
    pub fn is_missing(self) -> bool {
        self == Self::MISSING
    }
}

impl CauseDraftId {
    pub(crate) const UNATTRIBUTED: Self = Self(0);

    pub(crate) fn is_unattributed(self) -> bool {
        self == Self::UNATTRIBUTED
    }

    pub(super) fn public(self) -> CauseId {
        CauseId::new(
            self.get()
                .try_into()
                .expect("public capture cause arena exceeds u32"),
        )
    }
}

/// One word carried by native effects. The high bit distinguishes a direct
/// firing from a generic cause-node id; zero remains unattributed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub(crate) struct PackedCauseRef(u64);

impl PackedCauseRef {
    const FIRING_TAG: u64 = 1 << 63;
    pub(crate) const UNATTRIBUTED: Self = Self(0);

    pub(super) fn rule(firing: FiringId) -> Self {
        assert!(firing.get() != 0 && firing.get() < Self::FIRING_TAG);
        Self(Self::FIRING_TAG | firing.get())
    }

    pub(super) fn node(node: CauseDraftId) -> Self {
        assert!(!node.is_unattributed() && node.get() < Self::FIRING_TAG);
        Self(node.get())
    }

    pub(super) fn firing(self) -> Option<FiringId> {
        (self.0 & Self::FIRING_TAG != 0).then(|| FiringId::new(self.0 & !Self::FIRING_TAG))
    }

    pub(super) fn cause_node(self) -> Option<CauseDraftId> {
        (self != Self::UNATTRIBUTED && self.0 & Self::FIRING_TAG == 0)
            .then(|| CauseDraftId::new(self.0))
    }

    pub(super) fn is_unattributed(self) -> bool {
        self == Self::UNATTRIBUTED
    }
}

impl From<CauseDraftId> for PackedCauseRef {
    fn from(value: CauseDraftId) -> Self {
        Self::node(value)
    }
}

/// Stable reference back to one source command or original input row.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum SourceRef {
    /// Source commands, tests, and embedding callers use a stable ordinal.
    Synthetic(
        /// Frontend- or embedding-defined ordinal stable within the captured execution.
        u64,
    ),
    /// One physical row of an original `(input ...)` command.
    InputRow {
        /// Frontend-global source-command ordinal.
        command: u64,
        /// One-based physical line number in the source file.
        line: u64,
    },
}

/// Static recipe for resolving one endpoint of a positive check equality.
#[derive(Clone, Copy, Debug)]
pub struct CriterionEndpointSource {
    /// Source-ordered premise index in the check witness.
    pub(crate) premise: usize,
    /// Physical table-column index within that premise fact.
    pub(crate) column: usize,
    /// Query entry whose runtime value is checked at this endpoint.
    pub(crate) value: QueryEntry,
    /// Structural result sort and operation when the premise row names a constructor call.
    pub(crate) constructor: Option<(ReplaySortId, ReplayOpId)>,
}

impl CriterionEndpointSource {
    /// Creates an endpoint resolved from a non-constructor premise cell.
    pub fn premise(premise: usize, column: usize, value: QueryEntry) -> Self {
        Self {
            premise,
            column,
            value,
            constructor: None,
        }
    }

    /// Creates an endpoint whose premise row structurally denotes a constructor call.
    pub fn premise_constructor(
        premise: usize,
        column: usize,
        value: QueryEntry,
        sort: ReplaySortId,
        op: ReplayOpId,
    ) -> Self {
        Self {
            premise,
            column,
            value,
            constructor: Some((sort, op)),
        }
    }

    pub(crate) fn value(&self) -> &QueryEntry {
        &self.value
    }
}

/// Static witness and typed-equality layout for one positive check.
#[derive(Clone, Debug)]
pub struct CriterionCaptureSpec {
    pub(crate) check: u32,
    pub(crate) premises: Box<[AtomId]>,
    pub(crate) equalities: Box<[(CriterionEndpointSource, CriterionEndpointSource)]>,
}

impl CriterionCaptureSpec {
    /// Creates capture metadata for check `check` and its source-ordered premises.
    pub fn new(check: u32, premises: impl IntoIterator<Item = AtomId>) -> Self {
        Self {
            check,
            premises: premises.into_iter().collect(),
            equalities: Box::new([]),
        }
    }

    /// Adds the typed endpoint equalities whose support makes the check reproducible.
    pub fn with_equalities(
        mut self,
        equalities: impl IntoIterator<Item = (CriterionEndpointSource, CriterionEndpointSource)>,
    ) -> Self {
        self.equalities = equalities.into_iter().collect();
        self
    }
}

/// Static capture metadata retained with a compiled rule.
#[derive(Clone, Debug)]
pub struct FiringCaptureSpec {
    pub(crate) rule: u32,
    pub(crate) premises: Box<[AtomId]>,
    pub(crate) bindings: Box<[RuleBindingSpec]>,
}

/// One source-ordered binding retained by an effective firing.
#[derive(Clone, Copy, Debug)]
pub enum RuleBindingSpec {
    /// Capture a source-level variable from its premise cells or typed current value.
    Variable {
        /// Compiled query variable corresponding to the source-level binding.
        variable: Variable,
        /// Logical sort used to project the variable into a replay term.
        current_sort: ReplaySortId,
    },
    /// Retain a source-level literal or constant as an already-interned structural term.
    Constant {
        /// Structural replay term for the constant.
        term: ReplayTermId,
        /// Logical sort expected for `term`.
        sort: ReplaySortId,
    },
}

impl RuleBindingSpec {
    /// Creates a variable binding with its required replay sort.
    pub fn variable(variable: Variable, current_sort: ReplaySortId) -> Self {
        Self::Variable {
            variable,
            current_sort,
        }
    }

    /// Creates a binding to an already-interned structural constant.
    pub fn constant(term: ReplayTermId, sort: ReplaySortId) -> Self {
        Self::Constant { term, sort }
    }
}

impl FiringCaptureSpec {
    /// Creates capture metadata with the complete source-ordered binding layout.
    pub fn new(
        rule: u32,
        premises: impl IntoIterator<Item = AtomId>,
        bindings: impl IntoIterator<Item = RuleBindingSpec>,
    ) -> Self {
        Self {
            rule,
            premises: premises.into_iter().collect(),
            bindings: bindings.into_iter().collect(),
        }
    }
}

/// One exact physical premise cell containing a source-level binding.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PremiseOccurrence {
    /// Source-ordered premise index within the firing witness.
    pub premise: usize,
    /// Physical table-column index within that premise fact.
    pub column: usize,
}

/// Result of relocating one immutable logical fact after its native key changes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RekeyOutcome {
    /// The same fact remains live at its new key.
    Moved,
    /// An existing live fact absorbed the relocated fact at the colliding key.
    Absorbed(
        /// Live fact that survives the collision.
        FactId,
    ),
    /// A newly committed fact replaced the relocated fact at the colliding key.
    Replaced(
        /// Newly committed fact that succeeds the relocated occurrence.
        FactId,
    ),
}

/// One effective logical-row relocation. Pure rekeys preserve `fact`; a
/// collision records which live fact absorbed or replaced it. The equality
/// landmark is immutable and historically bounded at the rebuild decision.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct RekeyRecord {
    pub(crate) fact: FactId,
    pub(crate) position: HistoryPosition,
    pub(crate) equalities: EqualityLandmark,
    pub(crate) outcome: RekeyOutcome,
}

/// Exact positional child changes produced by one serial container rebuild.
///
/// The container's structural replay term remains immutable. Re-executing the
/// child equalities makes that same term denote the rebuilt native container.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ContainerDependency {
    pub(crate) wave: Wave,
    pub(crate) equalities: EqualityLandmark,
}

/// Capture-only logical identity for one container version. Borrowed views
/// expose the dependency itself; native refresh bookkeeping additionally
/// needs the exact structural producer that owned the raw container id.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ContainerVersionDependency {
    pub(crate) outer: EqualityEndpoint,
    pub(crate) dependency: Arc<ContainerDependency>,
}

#[derive(Clone)]
pub(crate) struct ContainerParentCandidate {
    pub(crate) endpoint: EqualityEndpoint,
    pub(crate) child_sorts: Arc<[ReplaySortId]>,
}

/// Forward-only overlay of existing immutable container terms during one
/// cloned-registry rebuild transaction. Source mappings remain historical;
/// only additional `(sort, raw) -> term` anchors are staged. Abort drops this
/// value without touching shared trace state.
#[derive(Clone, Debug, Default)]
pub(crate) struct ContainerAnchorJournal {
    pub(super) additions: HashMap<(ReplaySortId, Value), SmallVec<[ReplayTermId; 2]>>,
}

impl ContainerAnchorJournal {
    pub(super) fn additions(&self, sort: ReplaySortId, value: Value) -> Option<&[ReplayTermId]> {
        self.additions.get(&(sort, value)).map(SmallVec::as_slice)
    }

    pub(crate) fn is_empty(&self) -> bool {
        self.additions.is_empty()
    }

    pub(crate) fn extend(&mut self, other: Self) {
        for (key, terms) in other.additions {
            let current = self.additions.entry(key).or_default();
            for term in terms {
                if !current.contains(&term) {
                    current.push(term);
                }
            }
            current.sort_unstable_by_key(|term| term.get());
        }
    }
}

/// Exact causal classification of one effective native equality edge.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EqualityReason {
    /// A rule action explicitly proposed the union.
    RuleUnion(
        /// Grounded rule match that executed the union action.
        FiringId,
    ),
    /// A source action explicitly proposed the union.
    SourceUnion {
        /// Shared source cause unfolded lazily through [`TraceView::cause`].
        cause: CauseId,
    },
    /// A merge callback produced an equality while combining table rows.
    MergeFn {
        /// Shared exact cause root. Dependencies are unfolded lazily through
        /// [`TraceView::cause`]. The associated [`RawCause::Merge`] records
        /// when the callback read its operands; the equality record's position
        /// is the later time at which the deferred native edge was applied.
        cause: CauseId,
    },
    /// Rebuild or container maintenance derived the edge from earlier equalities.
    Congruence {
        /// Shared exact cause root; no growing prefix is copied per edge.
        cause: CauseId,
        /// Pre-maintenance history landmark from which the edge was derived.
        position: HistoryPosition,
    },
}

/// A typed native endpoint with an optional projected structural spelling.
///
/// A non-missing `term` names replay syntax, while [`ReplayTermId::MISSING`]
/// marks a deliberately raw maintenance landmark. Unlike
/// [`CriterionEndpointOccurrence`], this record never identifies a fact cell.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct EqualityEndpoint {
    /// Logical sort shared by the structural term and native value.
    pub sort: ReplaySortId,
    /// Stable structural replay term naming this endpoint.
    pub term: ReplayTermId,
    /// Opaque native value observed for this structural occurrence.
    pub raw: crate::Value,
}

/// Origin metadata parallel to a projected criterion endpoint.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CriterionEndpointOccurrence {
    /// The endpoint came from one exact historical fact cell.
    FactCell(
        /// Fact-and-column occurrence needed for liveness and equality support.
        FactCellRef,
    ),
    /// The endpoint has no historical fact-cell occurrence, for example a source constant.
    Current,
}

/// One typed equality observed in a successful check, paired with the exact
/// historical occurrence (if any) that supplied each endpoint.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CriterionEquality {
    /// Left and right typed structural endpoints observed by the check.
    pub endpoints: (EqualityEndpoint, EqualityEndpoint),
    /// Historical origins aligned with `endpoints`; source constants use
    /// [`CriterionEndpointOccurrence::Current`].
    pub occurrences: (CriterionEndpointOccurrence, CriterionEndpointOccurrence),
}

/// Exact native support retained for the first successful match of one check.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Criterion {
    /// Frontend identity of the positive check that first succeeded.
    pub check: u32,
    /// Execution wave in which the successful witness was observed.
    pub wave: Wave,
    /// Cross-stream position of the successful check event.
    pub position: HistoryPosition,
    /// Exact premise facts of the selected successful match, in source order.
    pub premises: Box<[FactId]>,
    /// Typed endpoint pairs and their aligned historical occurrence origins.
    pub equalities: Box<[CriterionEquality]>,
}

/// One effective replay-observable keyed-row removal.
///
/// The immutable victim fact retains the historical table/key row, so the
/// event needs no copied key payload. `cause` is the exact rule lane whose
/// head staged the removal.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Tombstone {
    /// Cross-stream position that ends the removed fact's native lifetime.
    pub position: HistoryPosition,
    /// Exact immutable row occurrence removed from the keyed table.
    pub removed_fact: FactId,
    /// Rule match whose head staged the removal.
    pub cause: FiringId,
}

/// One typed cell transition that maintenance must justify from earlier equality state.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct TypedCellEquality {
    /// Physical row column or positional container-child slot that changed.
    pub column: crate::ColumnId,
    /// Typed endpoint before the transition, or the left maintenance operand.
    pub left: EqualityEndpoint,
    /// Typed endpoint after the transition, or the right maintenance operand.
    pub right: EqualityEndpoint,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct EqualityLandmark {
    /// Pre-maintenance history landmark for equality and occurrence support.
    pub(crate) position: HistoryPosition,
    pub(crate) pairs: Box<[TypedCellEquality]>,
}

/// Point-in-time counts of externally addressable trace records.
#[derive(Clone, Copy, Debug)]
pub struct TraceTotals {
    /// Published immutable fact records.
    pub facts: u64,
    /// Published effective native equality edges.
    pub applied_equalities: u64,
    /// Retained keyed-row tombstones.
    pub removals: u64,
}

/// Caller-visible failure to cross an execution-trace lifecycle boundary.
///
/// These variants describe recoverable lifecycle and capability states rather
/// than internal publication corruption. Dense publication mismatches remain
/// panics at the finalization boundary.
#[derive(Clone, Copy, Debug, PartialEq, Eq, thiserror::Error)]
pub enum TraceLifecycleError {
    /// Trace-only control was requested before capture activation.
    #[error("trace capture is not enabled")]
    CaptureDisabled,
    /// The selected backend does not implement trace capture.
    #[error("this backend does not support trace capture")]
    UnsupportedBackend,
    /// A requested wave would move the global stamp backwards.
    #[error("trace waves must be globally monotone")]
    WaveRegression,
    /// Capture-enabled native execution failed before its publication barrier.
    #[error("cannot finalize trace after native execution failed before publication")]
    PoisonedExecution,
    /// At least one commit-local capture batch has not yet been published or dropped.
    #[error("cannot finalize trace while capture batches remain open")]
    OpenCaptureBatches,
    /// A commit-local capture batch containing records was dropped unpublished.
    #[error("cannot finalize trace after a capture batch was abandoned")]
    AbandonedCaptureBatch,
    /// Transactional native work has not yet drained through its table queue.
    #[error("cannot finalize trace while transactional native mutations remain queued")]
    ActiveNativeLeases,
}

/// Replay-relevant interpretation of one physical native table.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ReplayTableSchema {
    /// Logical table behavior that determines removal and merge replay.
    pub kind: ReplayTableKind,
    /// Number of leading physical columns forming the table key.
    pub key_columns: usize,
    /// Logical sort per physical column, or `None` for engine-only columns.
    pub columns: Arc<[Option<ReplaySortId>]>,
}

/// One immutable fact occurrence and physical column within its row.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct FactCellRef {
    /// Exact logical-row occurrence containing the cell.
    pub fact: FactId,
    /// Physical column of the cell within that fact.
    pub column: crate::ColumnId,
}

/// Historical view of a fact cell after applying its selected rekeys through a cutoff.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HistoricalFactCell {
    /// Exact immutable fact-and-column occurrence being followed.
    pub occurrence: FactCellRef,
    /// Structural term and raw value recorded when the fact was created.
    pub created: EqualityEndpoint,
    /// Same structural term paired with the raw value at the requested history position.
    pub endpoint: EqualityEndpoint,
    /// Rekey positions traversed from `created` to `endpoint`.
    pub rekeys: Box<[HistoryPosition]>,
}

/// One sufficient set of historical events that establishes a raw typed equality.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RawEqualitySupport {
    /// Effective native union edges selected from the equality forest.
    pub applied: Box<[AppliedEqualityId]>,
    /// Exact fact occurrences needed to anchor structural endpoints.
    pub facts: Box<[FactId]>,
    /// Row-relocation positions needed to follow raw cell values through history.
    pub rekeys: Box<[HistoryPosition]>,
}

/// One sufficient support set and the capture lower bounds for one structural checked
/// alias. Once established, the persistent alias lets a later grounded firing
/// reuse an e-class value after its constructor row has been deleted.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RawTermAvailability {
    /// Historical facts, rekeys, and union edges that justify the requested denotation.
    pub support: RawEqualitySupport,
    /// Child-first capture plans that constrain replay alias scheduling.
    pub aliases: Box<[ReplayAliasPlan]>,
}

/// Replay schedule for capturing one structural call occurrence as a
/// persistent checked alias. Entries are emitted child-first in structural
/// occurrence order. Each plan aligns with the corresponding call occurrence
/// in the enclosing firing binding's structural term.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ReplayAliasPlan {
    /// Exact constructor-row occurrence used to justify this alias. Pure and
    /// otherwise recomputable calls have no producer fact.
    pub producer: Option<FactId>,
    /// Inclusive lower bound after producer creation, inherited freshness, and
    /// the equality/fact/rekey support needed to address child keys. The
    /// current call's later output-to-parent bridge is deliberately excluded.
    pub ready_after: HistoryPosition,
    /// A refreshed ordered-container spelling and its structural descendants
    /// cannot canonicalize back to aliases from an earlier container version.
    pub fresh_after: Option<HistoryPosition>,
}

pub(super) fn combine_raw_equality_support(
    parts: impl IntoIterator<Item = RawEqualitySupport>,
) -> RawEqualitySupport {
    let mut applied = Vec::new();
    let mut facts = Vec::new();
    let mut rekeys = Vec::new();
    for part in parts {
        applied.extend(part.applied);
        facts.extend(part.facts);
        rekeys.extend(part.rekeys);
    }
    applied.sort_unstable();
    applied.dedup();
    facts.sort_unstable();
    facts.dedup();
    rekeys.sort_unstable();
    rekeys.dedup();
    RawEqualitySupport {
        applied: applied.into_boxed_slice(),
        facts: facts.into_boxed_slice(),
        rekeys: rekeys.into_boxed_slice(),
    }
}

/// Static source of one endpoint in a firing's equality-obligation layout.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FiringEqualitySource {
    /// Resolve the endpoint from an exact matched premise cell.
    Premise(
        /// Source-ordered premise and physical column to read.
        PremiseOccurrence,
    ),
    /// Use an already-projected structural constant endpoint.
    Constant(
        /// Typed constant spelling and its original native value.
        EqualityEndpoint,
    ),
}

/// Borrowed immutable row record exposed by a publication-complete [`TraceView`].
#[derive(Clone, Copy, Debug)]
pub struct RawFactRecord<'a> {
    /// Native table in which the occurrence was created.
    pub table: TableId,
    /// Cross-stream creation position used by liveness and replay scheduling.
    pub position: HistoryPosition,
    /// Exact firing or shared non-rule cause that created the fact.
    pub cause: CauseRef,
    /// Immutable native row values as recorded at creation.
    pub values: &'a [Value],
}

/// Borrowed record for one effective grounded rule match.
#[derive(Clone, Copy, Debug)]
pub struct Firing<'a> {
    /// Frontend identity of the rule that matched.
    pub rule: u32,
    /// Execution wave in which the match became effective.
    pub wave: Wave,
    /// Inclusive high-water mark of retained history visible to this firing.
    /// All lanes observed in one batch may share this value.
    pub history_cutoff: HistoryPosition,
    /// Exact source-ordered premise facts of the match.
    pub premises: &'a [FactId],
    /// Prior keyed rows read by merge effects of this match.
    pub merge_reads: &'a [FactId],
}

/// Borrowed non-rule cause whose dependencies a consumer can unfold lazily.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RawCause<'a> {
    /// A source command or physical input row owns the resulting event.
    Source(
        /// Stable identity of that command or input row.
        &'a SourceRef,
    ),
    /// Ordinary row rebuild changed typed cells of an existing fact.
    Rebuild {
        /// Fact whose pre-rebuild row supplies the maintenance dependency.
        prior_fact: FactId,
        /// Pre-rebuild history landmark for equality and occurrence support.
        position: HistoryPosition,
        /// Changed typed cells that the earlier equality state must justify.
        equalities: &'a [TypedCellEquality],
    },
    /// Native container interning equated structural versions without a prior row fact.
    ContainerCanonicalize {
        /// Pre-canonicalization history landmark for equality and occurrence support.
        position: HistoryPosition,
        /// Positional child equalities that justify the native container alias.
        equalities: &'a [TypedCellEquality],
    },
    /// Ordered-container mutation refreshed a structurally versioned prior fact.
    ContainerRefresh {
        /// Fact whose earlier container version must already be replay-visible.
        prior_fact: FactId,
        /// Pre-refresh history landmark for equality and occurrence support.
        position: HistoryPosition,
        /// Positional child transitions from the prior version to the refreshed version.
        equalities: &'a [TypedCellEquality],
    },
    /// A keyed-table merge combined an incoming cause with a prior live fact.
    Merge {
        /// Cause of the incoming row or action entering the merge.
        incoming: CauseRef,
        /// Existing fact read by the merge callback.
        prior_fact: FactId,
        /// Inclusive history boundary at which the callback read both rows.
        /// Deferred equality effects may be published after the replacement fact.
        history_cutoff: HistoryPosition,
    },
}

/// Typed native endpoint used to query historical equality connectivity.
///
/// It omits structural syntax intentionally; consumers request projection as
/// [`EqualityEndpoint`] only after selecting an event or occurrence.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RawEqualityEndpoint {
    /// Logical equality sort of the native value.
    pub sort: ReplaySortId,
    /// Opaque native value whose historical representative is queried.
    pub raw: Value,
}

/// One effective native union edge with its original raw proposal operands.
///
/// `left` and `right` are what egglog proposed to equate; `native_child` and
/// `native_parent` are the actual representative edge applied after prior
/// canonicalization, so neither pair can be reconstructed from the other.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RawAppliedEquality {
    /// Cross-stream position of the applied-union event.
    pub position: HistoryPosition,
    /// Raw typed left operand of the union proposal.
    pub left: RawEqualityEndpoint,
    /// Raw typed right operand of the union proposal.
    pub right: RawEqualityEndpoint,
    /// Native representative that remained the union-find parent.
    pub native_parent: Value,
    /// Native representative attached beneath `native_parent` by this edge.
    pub native_child: Value,
    /// Exact causal classification of the applied edge.
    pub reason: EqualityReason,
}

/// Lazily projected structural proposal for one applied native equality.
///
/// `left` and `right` preserve the structural occurrences the action proposed,
/// while `reason` preserves its exact causal classification. The event's
/// position and native representative edge remain in [`RawAppliedEquality`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProjectedEqualityProposal {
    /// Typed structural spelling of the proposal's left occurrence.
    pub left: EqualityEndpoint,
    /// Typed structural spelling of the proposal's right occurrence.
    pub right: EqualityEndpoint,
    /// Exact causal classification of the applied edge.
    pub reason: EqualityReason,
}

/// Borrowed record of one logical fact relocation caused by native canonicalization.
#[derive(Clone, Copy, Debug)]
pub struct RawRekeyRecord<'a> {
    /// Immutable fact occurrence whose raw row moved or ended.
    pub fact: FactId,
    /// Pre-rebuild history landmark, which can precede the rekey event position.
    pub equality_position: HistoryPosition,
    /// Typed cell transitions from the fact's prior row to its rebuilt row.
    pub equalities: &'a [TypedCellEquality],
    /// Whether the occurrence moved intact or ended in a key collision.
    pub outcome: RekeyOutcome,
}

/// Failure returned when a checked trace view cannot resolve historical data safely.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
pub enum TraceViewError {
    /// Capture has not reached the publication boundary required by borrowed views.
    #[error("trace history is not finalized: {0}")]
    NotFinalized(
        /// Finalization precondition that remains unsatisfied.
        &'static str,
    ),
    /// A trace lock was poisoned, so historical reads fail closed.
    #[error("trace lock is poisoned: {0}")]
    Poisoned(
        /// Lock or trace component that could not be read safely.
        &'static str,
    ),
    /// No published fact has the requested identity.
    #[error("unknown trace fact {0:?}")]
    UnknownFact(
        /// Unresolved fact identity.
        FactId,
    ),
    /// No published firing has the requested identity.
    #[error("unknown firing {0:?}")]
    UnknownFiring(
        /// Unresolved firing identity.
        FiringId,
    ),
    /// No published non-rule cause has the requested identity.
    #[error("unknown trace cause {0:?}")]
    UnknownCause(
        /// Unresolved shared cause identity.
        CauseId,
    ),
    /// No effective native equality edge has the requested identity.
    #[error("unknown applied equality {0:?}")]
    UnknownEquality(
        /// Unresolved applied-edge identity.
        AppliedEqualityId,
    ),
    /// No rekey event exists at the requested cross-stream position.
    #[error("unknown trace rekey at {0:?}")]
    UnknownRekey(
        /// Unresolved history position.
        HistoryPosition,
    ),
    /// No retained keyed-row removal exists at the requested dense index.
    #[error("unknown trace removal {0}")]
    UnknownRemoval(
        /// Zero-based removal-record index requested by the consumer.
        usize,
    ),
    /// The requested table has no registered replay schema.
    #[error("unknown replay table {0:?}")]
    UnknownTable(
        /// Native table identity missing replay metadata.
        TableId,
    ),
    /// Captured records violate an invariant required for sound historical replay.
    #[error("invalid trace history: {0}")]
    Invalid(
        /// Invariant violation detected while reading or explaining the trace.
        String,
    ),
    /// A requested fact occurrence ended before the queried history position.
    #[error(
        "trace fact {fact:?} ended at {ended_at:?} with successor {successor:?}; it is not live at {position:?}"
    )]
    FactNoLongerLive {
        /// Fact occurrence whose lifetime was queried.
        fact: FactId,
        /// Requested position after the occurrence's lifetime ended.
        position: HistoryPosition,
        /// Rekey or removal position that ended the occurrence.
        ended_at: HistoryPosition,
        /// Collision successor, or `None` when no fact inherited the row.
        successor: Option<FactId>,
    },
}

/// Opaque proof that both raw union endpoints were resolved through the
/// canonical typed replay-term map before native staging.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum EqualityTermRef {
    Exact(ReplayTermId),
    Site(TermOriginSiteId),
    Cell {
        origin: RowOriginRef,
        table: TableId,
        column: u16,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct PendingEqualityEndpoint {
    pub(crate) sort: ReplaySortId,
    pub(crate) raw: crate::Value,
    pub(crate) term: EqualityTermRef,
}

/// Capture-only transport proving both union operands have typed structural origins.
///
/// The record remains externally nameable for backend integration but is
/// hidden because consumers should read published [`RawAppliedEquality`] or
/// [`ProjectedEqualityProposal`] records instead of replaying proposals.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[doc(hidden)]
pub struct TypedEqualityProposal {
    pub(super) wave: Wave,
    pub(super) left: PendingEqualityEndpoint,
    pub(super) right: PendingEqualityEndpoint,
}

impl TypedEqualityProposal {
    pub(crate) fn wave(self) -> Wave {
        self.wave
    }

    pub(crate) fn left(self) -> PendingEqualityEndpoint {
        self.left
    }

    pub(crate) fn right(self) -> PendingEqualityEndpoint {
        self.right
    }
}
