#!/usr/bin/env python3
"""Generate sparse Math checkpoints with depth-dependent proof checks."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIRECTORY = ROOT / "benchmarks/math-microbenchmark"
CHECKPOINTS = tuple(range(0, 101, 10))
BASE_INCLUDE = "benchmarks/math-microbenchmark/base.egg"


def _integral_product(a: str, b: str, x: str) -> str:
    return f"(Integral (Mul {a} {b}) {x})"


def _integration_by_parts_rhs(a: str, b: str, x: str) -> str:
    integral_b = f"(Integral {b} {x})"
    return f"(Sub (Mul {a} {integral_b}) (Integral (Mul (Diff {x} {a}) {integral_b}) {x}))"


def checkpoint_check(iterations: int) -> str:
    """Return an equality first produced at the selected run depth."""

    x = '(Var "x")'
    a = f"(Cos {x})"
    b = x
    if iterations == 0:
        seed = _integral_product(a, b, x)
        return f"(check (= {seed} {seed}))"
    for _ in range(iterations - 1):
        a = f"(Diff {x} {a})"
        b = f"(Integral {b} {x})"
    return f"(check (= {_integral_product(a, b, x)} {_integration_by_parts_rhs(a, b, x)}))"


def checkpoint_path(iterations: int) -> Path:
    return OUTPUT_DIRECTORY / f"math-run-{iterations:03d}.egg"


def render_checkpoint(iterations: int) -> str:
    if iterations not in CHECKPOINTS:
        raise ValueError(f"unsupported Math checkpoint: {iterations}")
    description = (
        "The zero checkpoint verifies the seed before any rule iteration."
        if iterations == 0
        else "The final equality requires this many sequential integration-by-parts unfoldings."
    )
    return (
        "; Generated by scripts/generate_math_checkpoints.py.\n"
        f"; {description}\n"
        f'(include "{BASE_INCLUDE}")\n\n'
        f"(run {iterations})\n"
        f"{checkpoint_check(iterations)}\n"
    )


def write_checkpoints() -> None:
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for iterations in CHECKPOINTS:
        checkpoint_path(iterations).write_text(render_checkpoint(iterations), encoding="utf-8")


def check_checkpoints() -> bool:
    expected_paths = {checkpoint_path(iterations) for iterations in CHECKPOINTS}
    actual_paths = set(OUTPUT_DIRECTORY.glob("math-run-*.egg"))
    stale = sorted(
        path
        for path in expected_paths
        if not path.is_file() or path.read_text() != render_checkpoint(int(path.stem[-3:]))
    )
    stale.extend(sorted(actual_paths - expected_paths))
    for path in stale:
        print(f"stale generated Math checkpoint: {path.relative_to(ROOT)}", file=sys.stderr)
    return not stale


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write all checkpoint files")
    mode.add_argument("--check", action="store_true", help="check committed files without writing")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.write:
        write_checkpoints()
        return 0
    return 0 if check_checkpoints() else 1


if __name__ == "__main__":
    raise SystemExit(main())
