#!/usr/bin/env python3
"""Generate sparse Math checkpoints for the PLDI artifact scheduler."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIRECTORY = ROOT / "benchmarks/math-microbenchmark"
CHECKPOINTS = tuple(range(0, 101, 10))
BASE_INCLUDE = "benchmarks/math-microbenchmark/base.egg"
SCHEDULER_NAME = "paper-backoff"
MATCH_LIMIT = 1_000
BAN_LENGTH = 5
TABLES = (
    "Diff",
    "Integral",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Pow",
    "Ln",
    "Sqrt",
    "Sin",
    "Cos",
    "Const",
    "Var",
)
EXPECTED_TABLE_SIZES = {
    0: (2, 3, 7, 4, 4, 3, 2, 1, 1, 0, 1, 4, 3),
    10: (1_857, 3_771, 6_893, 1_838, 6_676, 3, 2, 1, 1, 1, 1, 5, 3),
    20: (3_224, 6_415, 11_992, 3_328, 13_316, 3, 2, 1, 1, 1, 1, 5, 3),
    30: (3_418, 20_018, 22_600, 9_490, 25_588, 3, 2, 1, 1, 1, 1, 5, 3),
    40: (31_217, 30_908, 50_484, 15_952, 34_902, 3, 2, 1, 1, 1, 1, 5, 3),
    50: (46_538, 63_511, 85_696, 28_719, 63_638, 3, 2, 1, 1, 1, 1, 5, 3),
    60: (72_807, 120_001, 147_289, 64_188, 111_376, 3, 2, 1, 1, 1, 1, 5, 3),
    70: (72_807, 120_669, 148_273, 64_676, 112_360, 3, 2, 1, 1, 1, 1, 5, 3),
    80: (99_489, 226_958, 290_263, 103_305, 281_971, 3, 2, 1, 1, 1, 1, 5, 3),
    90: (330_552, 226_958, 433_582, 103_305, 281_971, 3, 2, 1, 1, 1, 1, 5, 3),
    100: (387_116, 407_099, 623_586, 223_084, 440_029, 3, 2, 1, 1, 1, 1, 5, 3),
}
EXPECTED_TABLE_TOTALS = {iterations: sum(sizes) for iterations, sizes in EXPECTED_TABLE_SIZES.items()}


def checkpoint_check(iterations: int) -> str:
    """Return a source-visible correctness check valid at the checkpoint."""

    x = '(Var "x")'
    if iterations == 0:
        seed = f"(Integral (Mul (Cos {x}) {x}) {x})"
        return f"(check (= {seed} {seed}))"
    return f"(check (= (Add {x} (Cos {x})) (Add (Cos {x}) {x})))"


def checkpoint_path(iterations: int) -> Path:
    return OUTPUT_DIRECTORY / f"math-run-{iterations:03d}.egg"


def fixed_iteration_schedule(iterations: int) -> str:
    """Spell out every source iteration so no repeat implementation can stop early."""

    runs = "\n".join(f"  (run-with {SCHEDULER_NAME})" for _ in range(iterations))
    body = f"\n{runs}" if runs else ""
    return f"(run-schedule (seq{body}))"


def render_checkpoint(iterations: int) -> str:
    if iterations not in CHECKPOINTS:
        raise ValueError(f"unsupported Math checkpoint: {iterations}")
    description = f"The expected source-table total from the artifact is {EXPECTED_TABLE_TOTALS[iterations]:,}."
    table_sizes = "\n".join(f"(print-size {table})" for table in TABLES)
    return (
        "; Generated by scripts/generate_math_checkpoints.py.\n"
        f"; {description}\n"
        f'(include "{BASE_INCLUDE}")\n\n'
        f"(let-scheduler {SCHEDULER_NAME} "
        f"(back-off :match-limit {MATCH_LIMIT} :ban-length {BAN_LENGTH}))\n"
        f"{fixed_iteration_schedule(iterations)}\n"
        f"{checkpoint_check(iterations)}\n"
        f"{table_sizes}\n"
    )


def write_checkpoints() -> None:
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for iterations in CHECKPOINTS:
        checkpoint_path(iterations).write_text(render_checkpoint(iterations), encoding="utf-8")


def check_checkpoints() -> bool:
    expected_paths = {checkpoint_path(iterations) for iterations in CHECKPOINTS}
    actual_paths = set(OUTPUT_DIRECTORY.glob("math-run-*.egg"))
    stale = sorted(
        path
        for path in expected_paths
        if not path.is_file() or path.read_text() != render_checkpoint(int(path.stem[-3:]))
    )
    stale.extend(sorted(actual_paths - expected_paths))
    for path in stale:
        print(f"stale generated Math checkpoint: {path.relative_to(ROOT)}", file=sys.stderr)
    return not stale


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write all checkpoint files")
    mode.add_argument("--check", action="store_true", help="check committed files without writing")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.write:
        write_checkpoints()
        return 0
    return 0 if check_checkpoints() else 1


if __name__ == "__main__":
    raise SystemExit(main())
