"""Prepare standalone paper workloads from pinned author sources.

This command owns acquisition/correctness evidence, never benchmark observations.
The portable manifest and standalone workloads can be committed; local evidence
and resumable source captures are kept separately.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import re
import shutil
import time
import urllib.request
from pathlib import Path
from typing import Any

from benchmarking.suites import MANIFEST_RELATIVE_PATH, SAFETY_POLICY, CorpusOutcome
from scripts.hardboiled_replay import egglog_forms
from scripts.reproduction_inventory import FAMILIES, ROOT, expected_cases, select_cases
from scripts.reproduction_process import exclusive_job
from scripts.source_tools import Preparation, acquire_source, sha256_file

STOP_STATUSES = {"resource-stopped", "memory-limit", "cancelled", "interrupted"}


def generation_identity(family: str, recipe: dict[str, Any]) -> str:
    """Bind generated bytes and admission contracts, not process/resume policy."""
    shared = {
        "reproduction_inventory.py",
        "hardboiled_replay.py",
    }
    if family == "hardboiled":
        shared.add("reproduction_published.py")
    inputs = {path for path in (ROOT / "scripts").glob("*.py") if path.name in shared or family in path.stem}
    materializer = ROOT / "scripts/paper_benchmarks/materialize.py"
    if family in {"eggcc", "churchroad", "misaal", "dialegg"} and materializer.is_file():
        inputs.add(materializer)
    inputs.update(
        path
        for path in (ROOT / "benchmarks/reproduction").rglob("*")
        if path.is_file() and family in path.relative_to(ROOT / "benchmarks/reproduction").as_posix()
    )
    if family == "math-growth":
        inputs.add(ROOT / recipe["input"])
    digest = hashlib.sha256(json.dumps(recipe, sort_keys=True).encode())
    for path in sorted(inputs):
        digest.update(str(path.relative_to(ROOT)).encode() + b"\0" + path.read_bytes())
    for filename, functions in {
        "suite_reproduction.py": {"capture_source_file", "capture_case", "publish_workload"},
        "reproduction_validation.py": {
            "eggcc_root_contract",
            "churchroad_circuit_contract",
            "_sexpr",
            "static_extract_model",
            "static_native_contract",
            "materialize_static_native_contract",
            "validate_static_native_output",
        },
    }.items():
        path = ROOT / "scripts" / filename
        if path.is_file():
            nodes: list[ast.stmt] = [
                node
                for node in ast.parse(path.read_text()).body
                if filename == "reproduction_validation.py"
                and isinstance(node, (ast.Assign, ast.AnnAssign))
                or isinstance(node, ast.FunctionDef)
                and node.name in functions
            ]
            digest.update(filename.encode() + b"\0" + ast.dump(ast.Module(body=nodes, type_ignores=[])).encode())
    return digest.hexdigest()


def eggcc_environment_identity(settings: dict[str, Any], recipe: dict[str, Any]) -> dict[str, Any]:
    """Check the prepared executables, runtime artifacts and selected author inputs."""
    paths = settings["paths"]
    inputs = {Path(paths["binary"]), *(Path(path) for path in settings["identity_paths"])}
    inputs.update(Path(paths["checkout"]) / source for source in recipe["programs"])
    for path in tuple(inputs):
        if path.name == "build-products.json":
            products = json.loads(path.read_text())
            if any(sha256_file(Path(name)) != digest for name, digest in products.items()):
                raise ValueError("prepared Eggcc build product changed")
            inputs.update(Path(name) for name in products)
    return {
        "settings": {**settings, "paths": {key: value for key, value in paths.items() if key != "egglog"}},
        "files": {str(path): sha256_file(path) for path in sorted(inputs)},
    }


def portable_reason(reason: str | None, fallback: str) -> str | None:
    """Keep concise source blockers while excluding local paths and diagnostic dumps."""
    if reason is None:
        return None
    summary = reason.partition("; see ")[0]
    if summary.startswith("missing LLVM18/MLIR frontend prerequisite: "):
        summary = "missing LLVM18/MLIR frontend prerequisite: " + Path(summary.split(": ", 1)[1]).name
    if len(summary) > 240 or "\n" in summary or re.search(r"(?:^|[\s'\"])/|[A-Za-z]:\\", summary):
        return fallback
    return summary


def write_manifest(directory: Path, manifest: dict[str, Any]) -> None:
    """Publish portable identities and bind private resume state to those exact bytes."""
    case_files = {case["id"]: set(case["workloads"]) for case in manifest.get("cases", [])}
    if "cases" in manifest:
        for workload in manifest["workloads"]:
            workload["aliases"] = [
                alias for alias in workload["aliases"] if workload["file"] in case_files.get(alias["case"], ())
            ]
        manifest["workloads"] = [workload for workload in manifest["workloads"] if workload["aliases"]]
    public = {
        "sources": manifest.get("sources", {}),
        "preparation": manifest.get("preparation", {}),
        "cases": [
            {
                **{key: case[key] for key in ("id", "family", "source", "status", "workloads") if key in case},
                "reason": portable_reason(
                    case.get("portable_reason", case.get("reason")),
                    f"source preparation: {case.get('status', 'blocked')}",
                ),
            }
            for case in manifest.get("cases", [])
        ],
        "workloads": [
            {
                key: workload[key]
                for key in ("file", "sha256", "facts_sha256", "facts", "aliases", "adaptations")
                if key in workload
            }
            for workload in manifest["workloads"]
        ],
    }
    content = json.dumps(public, indent=2) + "\n"
    local = directory / ".local"
    local.mkdir(parents=True, exist_ok=True)
    state = {
        "manifest_sha256": hashlib.sha256(content.encode()).hexdigest(),
        "manifest": {key: value for key, value in manifest.items() if key != "outcomes"},
    }
    for path, encoded in (
        (directory / "manifest.json", content),
        (local / "preparation.json", json.dumps(state, indent=2) + "\n"),
    ):
        if not path.is_file() or path.read_text() != encoded:
            temporary = local / (path.stem + ".tmp")
            temporary.write_text(encoded)
            temporary.replace(path)


def publish_workload(
    directory: Path, manifest: dict[str, Any], case: dict[str, Any], source: Path, order: int, adaptations: list[str]
) -> None:
    """Keep one immutable file per identity and all independent source aliases."""
    data = source.read_bytes()
    forms = [tokens for _, _, tokens in egglog_forms(data.decode())]
    if not any(tokens[1] in {"check", "extract"} for tokens in forms):
        raise ValueError("source emitted a setup/helper call without an output query")
    if any(tokens[1] in {"include", "input", "prove", "prove-extract"} for tokens in forms):
        raise ValueError("workload must be self-contained and treatment-neutral")
    digest = hashlib.sha256(data).hexdigest()
    target = directory / (digest + ".egg")
    if target.exists() and target.read_bytes() != data:
        raise ValueError("content-addressed corpus file changed")
    if not target.exists():
        target.write_bytes(data)
    workload = next((row for row in manifest["workloads"] if row["file"] == target.name), None)
    if workload is None:
        workload = {
            "file": target.name,
            "sha256": "sha256:" + digest,
            "facts_sha256": "",
            "aliases": [],
            "adaptations": adaptations,
        }
        manifest["workloads"].append(workload)
    for adaptation in adaptations:
        if adaptation not in workload["adaptations"]:
            workload["adaptations"].append(adaptation)
    alias = {"case": case["id"], "order": order}
    if alias not in workload["aliases"]:
        workload["aliases"].append(alias)
    if target.name not in case["workloads"]:
        case["workloads"].append(target.name)


def capture_source_file(case: dict[str, Any], recipe: dict[str, Any], directory: Path) -> tuple[Path, list[str]]:
    """Fetch published programs and apply only their documented compatibility changes."""
    directory.mkdir(parents=True, exist_ok=True)
    family = case["family"]
    if family == "math-growth":
        source = ROOT / case["source"]
        return source, ["original seven Math seeds and 24 rules; simple schedule; iteration-11 equality"]
    url = f"{recipe['repository'].replace('https://github.com/', 'https://raw.githubusercontent.com/')}/{recipe['revision']}/{case['source']}"
    original = directory / "source.egg"
    if not original.exists():
        with urllib.request.urlopen(url, timeout=60) as response, original.open("wb") as stream:
            shutil.copyfileobj(response, stream)
    source = original.read_text()
    if family == "hardboiled":
        from scripts.hardboiled_replay import omit_unexecuted_higher_order_rules
        from scripts.reproduction_published import published_entries, verify_input

        verify_input(published_entries(recipe)[case["id"]], original.read_bytes())
        adapted = omit_unexecuted_higher_order_rules(source)
        changes = ["omit statically unscheduled higher-order rules"] if adapted != source else []
    else:
        from scripts.luminal import luminal_witness

        root, check = luminal_witness(source)
        adapted = source.rstrip() + "\n\n" + check + "\n"
        changes = [f"append equality between seeded {root} Iota and its derived KernelIota lowering"]
    (directory / "source.json").write_text(
        json.dumps({"url": url, "sha256": sha256_file(original), "adaptations": changes}, indent=2) + "\n"
    )
    replay = directory / "replay.egg"
    replay.write_text(adapted)
    return replay, changes


def prepare_family(
    family: str,
    directory: Path,
    engine: Path,
    recipe: dict[str, Any],
    *,
    case_ids: list[str] | None = None,
    timeout_sec: float = 300,
) -> dict[str, Any]:
    """Acquire/build the source environment once, with no historical local prerequisites."""
    from scripts.reproduction_prepare_churchroad import REVISIONS as churchroad_pins
    from scripts.reproduction_prepare_dialegg import DIALEGG_REVISION as dialegg_revision
    from scripts.reproduction_prepare_eggcc import REVISION as eggcc_revision
    from scripts.reproduction_prepare_misaal import MISAAL_REVISION

    expected = {
        "eggcc": ("https://github.com/egraphs-good/eggcc", eggcc_revision),
        "dialegg": ("https://github.com/AzizZayed/dialegg-cgo-artifact", dialegg_revision),
        "churchroad": ("https://github.com/gussmith23/churchroad", churchroad_pins["churchroad"][1]),
        "misaal": ("https://github.com/RafaeNoor/MISAAL", MISAAL_REVISION),
    }
    if (recipe["repository"].removesuffix(".git"), recipe["revision"]) != expected[family]:
        raise ValueError(f"{family} recipe differs from its source adapter pin")
    if family == "eggcc":
        from scripts.reproduction_prepare_eggcc import prepare_eggcc

        result = prepare_eggcc(directory, engine)
    elif family == "dialegg":
        from scripts.reproduction_prepare_dialegg import prepare_dialegg

        result = prepare_dialegg(directory, engine)
    elif family == "churchroad":
        from scripts.reproduction_prepare_churchroad import prepare_churchroad

        result = prepare_churchroad(directory, engine)
        if result["status"] == "success":
            driver = Preparation(directory, continuation=True)
            later = recipe["later_evaluation"]
            source = acquire_source(driver, "churchroad-evaluation", later["repository"], later["revision"])
            settings_path = Path(result["settings"])
            settings = json.loads(settings_path.read_text())
            settings[family]["paths"]["source_root"] = str(source)
            settings_path.write_text(json.dumps(settings, indent=2) + "\n")
    elif family == "misaal":
        from scripts.reproduction_prepare_misaal import prepare_exports

        result = prepare_exports(directory, engine, case_ids=case_ids, timeout_sec=timeout_sec)
    else:
        raise ValueError(f"no source generator for {family}")
    if result["status"] != "success":
        return result
    settings = json.loads(Path(result["settings"]).read_text())[family]
    if family == "dialegg":
        from scripts.dialegg_capture import prepare_complete_dialegg

        build = directory / "frontend"
        build.mkdir()
        binary, evidence = prepare_complete_dialegg(
            Path(settings["paths"]["llvm18_prefix"]), Path(settings["paths"]["dialegg_source"]), build, 600
        )
        if binary is None:
            failure = evidence["builds"][-1]
            return {"status": failure["status"], "reason": "DialEgg frontend build failed"}
        settings["paths"]["prepared_frontend"] = str(binary)
    return {"status": "success", "settings": settings}


def capture_case(
    case: dict[str, Any], settings: dict[str, Any], directory: Path, engine: Path, timeout_sec: float
) -> dict[str, Any]:
    """Stop at completed Egglog work; downstream code generation is not required."""
    paths = {key: Path(value) for key, value in settings["paths"].items() if value is not None}
    family = case["family"]
    if family in {"eggcc", "churchroad"}:
        from scripts.suite_capture_eggcc_churchroad import capture_complete

        config = {**case, **case["configuration"]}
        if case.get("source_set") == "later_evaluation":
            config["source"] = str(paths["source_root"] / case["source"])
        return capture_complete(
            family,
            [config],
            directory,
            paths["checkout"],
            paths["binary"],
            engine,
            timeout_sec=timeout_sec,
            validate_ordinary=False,
        )[0]
    if family == "dialegg":
        from scripts.dialegg_capture import capture_complete_dialegg

        directory.mkdir(parents=True)
        args = argparse.Namespace(**paths, timeout_sec=timeout_sec, validate_ordinary=False)
        record: dict[str, Any] = capture_complete_dialegg(args, [case["id"]], directory)["cases"][case["id"]]
        return record
    from scripts.misaal_reproduction import capture_misaal

    request = paths["requests"] / (case["id"] + ".json")
    if json.loads(request.read_text())["source_timeout_sec"] != timeout_sec:
        raise ValueError("MISAAL prepared timeout differs from the source capture request")
    return capture_misaal(request, directory)


def reproduce(
    directory: Path, families: list[str], names: list[str], engine: Path, *, timeout_sec: float = 300
) -> dict[str, Any]:
    """Resume generated inputs; persist every preparation outcome before another launch."""
    from scripts import reproduction_validation
    from scripts.dialegg_capture import run_complete_command
    from scripts.reproduction_validation import validate_capture
    from scripts.validate_benchmarks import record_outcome

    sources = json.loads((ROOT / "benchmarks/sources.json").read_text())
    cases = expected_cases(sources)
    selected = select_cases(cases, families, names)
    directory = directory.resolve()
    directory.mkdir(parents=True, exist_ok=True)
    manifest_path = directory / "manifest.json"
    original = manifest_path.read_bytes() if manifest_path.is_file() else b""
    old = json.loads(original) if original else {}
    state_path = directory / ".local/preparation.json"
    if state_path.is_file():
        state = json.loads(state_path.read_text())
        if state["manifest_sha256"] == hashlib.sha256(original).hexdigest():
            old = state["manifest"]
    outcomes_path = directory / ".local/outcomes.json"
    old_cases = {case["id"]: case for case in old.get("cases", [])}
    preparation = {
        family: generation_identity(family, sources[family])
        for family in dict.fromkeys(case["family"] for case in cases)
    }
    reusable = {
        family for family, identity in preparation.items() if old.get("preparation", {}).get(family) == identity
    }
    validation_identity = {
        "engine_sha256": sha256_file(engine),
        "timeout_sec": timeout_sec,
        "validation_sha256": sha256_file(Path(reproduction_validation.__file__)),
    }
    manifest: dict[str, Any] = {
        "sources": sources,
        "preparation": preparation,
        "cases": [],
        "workloads": [],
        "outcomes": json.loads(outcomes_path.read_text()) if outcomes_path.is_file() else [],
        "environments": {
            family: environment for family, environment in old.get("environments", {}).items() if family in reusable
        },
    }
    for case in cases:
        previous = old_cases.get(case["id"])
        row = {**case, "status": "pending", "workloads": []}
        if previous and case["family"] in reusable:
            row = {**case, **previous}
        manifest["cases"].append(row)
    selected_ids = {case["id"] for case in selected}
    current_files = {name for case in manifest["cases"] for name in case["workloads"]}
    manifest["workloads"] = [row for row in old.get("workloads", []) if row["file"] in current_files]
    for workload in manifest["workloads"]:
        if "sha256:" + sha256_file(directory / workload["file"]) != workload["sha256"]:
            raise ValueError(f"prepared workload changed: {workload['file']}")
    write_manifest(directory, manifest)
    job_root = ROOT / "benchmarks/local/reproduction" / str(time.time_ns())
    job_root.mkdir(parents=True)
    environments: dict[str, dict[str, Any]] = {}
    for case in manifest["cases"]:
        if case["id"] not in selected_ids:
            continue
        if case["workloads"] and case.get("validation") == validation_identity:
            if case.get("revalidation", {}).get("status", "success") != "success":
                case.pop("revalidation")
                write_manifest(directory, manifest)
            continue
        if case.get("output_limit") == validation_identity:
            continue
        family = case["family"]
        attempt = job_root / "cases" / case["id"]
        attempt.mkdir(parents=True)
        if case["workloads"] and (
            not case.get("capture")
            or case.get("validation", {}).get("validation_sha256") == validation_identity["validation_sha256"]
        ):
            # Frozen programs are the portable source of truth. Revalidation must
            # not require author compilers or change their published provenance.
            case["evidence"] = str(attempt.relative_to(ROOT))
            for order, name in enumerate(case["workloads"]):
                try:
                    process = run_complete_command(
                        [str(engine), str(directory / name)], ROOT, attempt / f"ordinary-{order}", timeout_sec
                    )
                    status, reason = process.status, process.message
                except (OSError, ValueError, RuntimeError) as error:
                    status = "resource-stopped" if "guard refused" in str(error) else "failure"
                    reason = str(error)
                case["revalidation"] = {"status": status, "reason": reason}
                if status == "output-limit":
                    case["output_limit"] = validation_identity
                if status in STOP_STATUSES:
                    workload = next(row for row in manifest["workloads"] if row["file"] == name)
                    outcome: CorpusOutcome = {
                        "file_sha256": workload["sha256"],
                        "fact_directory_sha256": workload.get("facts_sha256", ""),
                        "binary_sha256": f"sha256:{validation_identity['engine_sha256']}",
                        "timeout_sec": int(timeout_sec),
                        "disequality_encoding": "nee",
                        "kind": "safety",
                        "policy": SAFETY_POLICY,
                        "status": "deferred",
                        "reason": reason or status,
                    }
                    record_outcome(manifest_path, outcome)
                    manifest["outcomes"] = json.loads(outcomes_path.read_text())
                    write_manifest(directory, manifest)
                    raise RuntimeError(
                        f"{case['id']}: resource guard stopped preparation: {reason or status}; "
                        "later cases remain pending"
                    )
                if status != "success":
                    break
            else:
                case["validation"] = validation_identity
            write_manifest(directory, manifest)
            print(f"{case['id']}: ordinary revalidation {case['revalidation']['status']}", flush=True)
            continue
        case.pop("validation", None)
        case.update(status="blocked", reason=None, portable_reason=None, evidence=str(attempt.relative_to(ROOT)))
        try:
            captured = None
            if case.get("capture"):
                path = ROOT / case["capture"]
                if sha256_file(path) != case["capture_sha256"]:
                    raise ValueError("retained source capture changed")
                captured = json.loads(path.read_text())
            if family in {"math-growth", "luminal", "hardboiled"}:
                if captured is None:
                    replay, adaptations = capture_source_file(case, sources[family], attempt)
                    captured = {"replay": str(replay), "sha256": sha256_file(replay), "adaptations": adaptations}
                replay = Path(captured["replay"])
                if sha256_file(replay) != captured["sha256"]:
                    raise ValueError("retained published replay changed")
                capture_path = attempt / "capture.json"
                capture_path.write_text(json.dumps(captured, indent=2) + "\n")
                case.update(capture=str(capture_path.relative_to(ROOT)), capture_sha256=sha256_file(capture_path))
                process = run_complete_command(
                    [str(engine), str(replay.resolve())], ROOT, attempt / "ordinary", timeout_sec
                )
                if process.status == "output-limit":
                    case["output_limit"] = validation_identity
                if process.status != "success":
                    case.update(
                        status="blocked",
                        reason=f"ordinary replay: {process.status}: {process.message or ''}",
                        portable_reason=f"ordinary replay: {process.status}",
                    )
                    if process.status in STOP_STATUSES:
                        raise RuntimeError("resource safety stop")
                else:
                    publish_workload(directory, manifest, case, replay, 0, captured["adaptations"])
                    case.update(status="ready", reason=None)
            else:
                if captured is None and family == "eggcc":
                    from scripts.reproduction_prepare_eggcc import GUROBI_BLOCKER

                    if case["configuration"] == GUROBI_BLOCKER["configuration"]:
                        case["reason"] = case["portable_reason"] = GUROBI_BLOCKER["reason"]
                        write_manifest(directory, manifest)
                        continue
                    saved_environment = manifest["environments"].get(family)
                    if saved_environment and family not in environments:
                        try:
                            settings = saved_environment["settings"]
                            if eggcc_environment_identity(settings, sources[family]) == saved_environment["identity"]:
                                settings["paths"]["egglog"] = str(engine)
                                environments[family] = {"status": "success", "settings": settings}
                        except (OSError, ValueError, KeyError):
                            pass  # Missing/changed native products must be prepared again.
                if captured is None and family not in environments:
                    environments[family] = prepare_family(
                        family,
                        job_root / family,
                        engine,
                        sources[family],
                        case_ids=[
                            row["id"]
                            for row in manifest["cases"]
                            if row["family"] == family and row["id"] in selected_ids and row["status"] != "ready"
                        ],
                        timeout_sec=timeout_sec,
                    )
                    prepared = environments[family]
                    if family == "eggcc" and prepared["status"] == "success" and prepared["settings"].get("paths"):
                        settings = prepared["settings"]
                        manifest["environments"][family] = {
                            "settings": settings,
                            "identity": eggcc_environment_identity(settings, sources[family]),
                        }
                        write_manifest(directory, manifest)
                environment: dict[str, Any] = (
                    environments[family] if captured is None else {"status": "success", "settings": {}}
                )
                if environment["status"] != "success":
                    case.update(
                        reason=environment.get("reason", environment["status"]),
                        portable_reason=environment.get("reason") or f"source preparation: {environment['status']}",
                    )
                    if environment["status"] in STOP_STATUSES:
                        raise RuntimeError("resource safety stop")
                else:
                    settings = environment["settings"]
                    blocker = next(
                        (
                            row
                            for row in settings.get("configuration_blockers", [])
                            if all(
                                case["configuration"].get(key) == value for key, value in row["configuration"].items()
                            )
                            and (not row.get("case_ids") or case["id"] in row["case_ids"])
                        ),
                        None,
                    )
                    if blocker:
                        case["reason"] = case["portable_reason"] = blocker["reason"]
                    else:
                        if captured is None:
                            captured = capture_case(case, settings, attempt / "capture", engine, timeout_sec)
                        capture_path = attempt / "capture.json"
                        capture_path.write_text(json.dumps(captured, indent=2, default=str) + "\n")
                        if captured["status"] in STOP_STATUSES:
                            case["reason"] = captured.get("reason", captured["status"])
                            case["portable_reason"] = captured.get("reason") or f"source capture: {captured['status']}"
                            raise RuntimeError("resource safety stop")
                        if "output-limit" in {captured["status"], captured.get("process", {}).get("status")}:
                            case["output_limit"] = validation_identity
                        if captured["status"] not in {
                            "reproduced",
                            "ordinary-validation-pending",
                            "ordinary-validation-failed",
                        }:
                            case["reason"] = captured.get("reason") or f"source capture: {captured['status']}"
                            case["portable_reason"] = captured.get("reason") or f"source capture: {captured['status']}"
                            write_manifest(directory, manifest)
                            continue
                        case.update(
                            capture=str(capture_path.relative_to(ROOT)), capture_sha256=sha256_file(capture_path)
                        )
                        previous_validation = None
                        if case.get("validation_receipt"):
                            receipt = ROOT / case["validation_receipt"]
                            if sha256_file(receipt) != case["validation_receipt_sha256"]:
                                raise ValueError("retained validation receipt changed")
                            previous_validation = json.loads(receipt.read_text())
                        validation = validate_capture(
                            captured,
                            engine,
                            attempt / "validation",
                            timeout_sec=timeout_sec,
                            previous=previous_validation,
                        )
                        receipt = attempt / "validation/validation.json"
                        if receipt.is_file():
                            case.update(
                                validation_receipt=str(receipt.relative_to(ROOT)),
                                validation_receipt_sha256=sha256_file(receipt),
                            )
                        reason = validation.get("reason")
                        public_reason = (
                            (
                                reason
                                if validation["status"] == "blocked"
                                else f"ordinary replay: {validation['status']}"
                            )
                            if reason
                            else None
                        )
                        if not reason and captured.get("failed_invocations"):
                            reason = public_reason = (
                                f"{len(captured['failed_invocations'])} Egglog calls failed; retained complete calls"
                            )
                        parent_status = captured.get("process", {}).get("status")
                        if not reason and (
                            captured.get("parent_failure") or parent_status in {"failure", "timed-out", "output-limit"}
                        ):
                            parent_outcome = {"timed-out": "timed out", "output-limit": "hit output limit"}.get(
                                parent_status, "failed"
                            )
                            reason = public_reason = (
                                f"Source parent {parent_outcome} after complete Egglog calls; see capture evidence"
                            )
                        case.update(reason=reason, portable_reason=public_reason)
                        sessions = captured.get("sessions") or captured.get("invocations", [])
                        orders = {
                            session.get("replay") or session.get("standalone"): session.get("source_order", index)
                            for index, session in enumerate(sessions)
                        }
                        for workload in validation["workloads"]:
                            publish_workload(
                                directory,
                                manifest,
                                case,
                                Path(workload),
                                orders[workload],
                                ["source/API modernization and output contracts (see capture)"],
                            )
                        case["status"] = "ready" if case["workloads"] else "blocked"
                        if validation["status"] in STOP_STATUSES:
                            raise RuntimeError("resource safety stop")
            case["evidence"] = str(attempt.relative_to(ROOT))
            case["validation"] = validation_identity
        except (OSError, ValueError, RuntimeError) as error:
            case["reason"] = case.get("reason") or str(error)
            case["portable_reason"] = case.get("portable_reason") or str(error)
            if str(error) == "resource safety stop" or "guard refused" in str(error):
                write_manifest(directory, manifest)
                raise RuntimeError(
                    f"{case['id']}: resource guard stopped preparation: {case['reason']}; later cases remain pending"
                ) from error
        write_manifest(directory, manifest)
        print(f"{case['id']}: {case['status']} ({len(case['workloads'])} workloads)", flush=True)
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--family", action="append", choices=FAMILIES)
    parser.add_argument("--case", action="append", default=[])
    parser.add_argument("--output", type=Path, default=ROOT / MANIFEST_RELATIVE_PATH.parent)
    parser.add_argument("--engine", type=Path)
    parser.add_argument("--timeout-sec", type=float, default=300)
    args = parser.parse_args()
    if args.timeout_sec <= 0:
        parser.error("--timeout-sec must be positive")
    try:
        with exclusive_job(ROOT / "benchmarks/local/reproduction/.heavy-job.lock"):
            if args.engine is None:
                directory = ROOT / "benchmarks/local/reproduction" / ("engine-" + str(time.time_ns()))
                directory.mkdir(parents=True)
                driver = Preparation(directory)
                driver.step(
                    "build-engine",
                    ["cargo", "build", "--locked", "--release", "-j1", "-p", "egglog-experimental"],
                    cwd=ROOT,
                    timeout=1800,
                )
                args.engine = ROOT / os.environ.get("CARGO_TARGET_DIR", "target") / "release/egglog-experimental"
            if not args.engine.is_file():
                raise ValueError(f"ordinary replay engine is missing: {args.engine}")
            manifest = reproduce(
                args.output,
                args.family or list(FAMILIES),
                args.case,
                args.engine.resolve(),
                timeout_sec=args.timeout_sec,
            )
        print((args.output / "manifest.json").resolve())
        return int(
            any(
                case["status"] == "pending" or case.get("revalidation", {}).get("status", "success") != "success"
                for case in select_cases(manifest["cases"], args.family or list(FAMILIES), args.case)
            )
        )

    except (OSError, ValueError, RuntimeError) as error:
        parser.exit(2, f"error: {error}\n")


if __name__ == "__main__":
    raise SystemExit(main())
