use egglog::{
    ArcSort, CommandMacro, Context, Error, FullState, RawValues, TypeError, TypeInfo, Value,
    Write as EgglogWrite,
    ast::{
        Action, Actions, Command, Expr, Fact, Macro, ParseError, Parser, Rule, RuleEvalMode,
        Schema, Sexp, Span,
    },
    util::SymbolGen,
};
use std::{collections::BTreeMap, fmt::Write, sync::Arc};
use std::{fmt, str::FromStr};

const PLACEHOLDER: &str = "@disequal";
const TRUTH_SORT: &str = "@disequality-truth";
const TRUE: &str = "@disequality-true";
const FALSE: &str = "@disequality-false";

/// Published encodings supported by the `(disequal lhs rhs)` action.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum DisequalityEncoding {
    /// The five-rule equality embedding (EE) from Zakhour et al.
    #[default]
    EqualityEmbedding,
    /// Equality embedding with self-equality contradiction detection (OEE).
    OptimizedEqualityEmbedding,
    /// A private `ne` e-node with self-loop contradiction detection (NEE).
    NegatedEqualityEmbedding,
    /// A symmetric database relation over e-classes (DE).
    DisequalityEdges,
}

impl DisequalityEncoding {
    pub const POSSIBLE_VALUES: &str = "ee, oee, nee, de";

    pub const fn cli_name(self) -> &'static str {
        match self {
            Self::EqualityEmbedding => "ee",
            Self::OptimizedEqualityEmbedding => "oee",
            Self::NegatedEqualityEmbedding => "nee",
            Self::DisequalityEdges => "de",
        }
    }
}

impl FromStr for DisequalityEncoding {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "ee" => Ok(Self::EqualityEmbedding),
            "oee" => Ok(Self::OptimizedEqualityEmbedding),
            "nee" => Ok(Self::NegatedEqualityEmbedding),
            "de" => Ok(Self::DisequalityEdges),
            _ => Err(format!(
                "unknown disequality encoding `{value}`; expected one of: {}",
                Self::POSSIBLE_VALUES
            )),
        }
    }
}

impl fmt::Display for DisequalityEncoding {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.cli_name())
    }
}

/// Low-level writer for bulk-loading the representation generated by
/// [`DisequalityEncoding`].
///
/// Construct this inside one [`egglog::EGraph::update`] call after a source
/// `(disequal ...)` command has installed support for `sort`. Each [`Self::add`]
/// is the database-level equivalent of the action emitted by the command
/// macro. The enclosing update batches all writes behind one flush.
///
/// This API accepts raw [`Value`]s, so the caller must ensure both operands
/// belong to `sort`. `EGraph::update` rejects proof-enabled e-graphs because
/// these direct writes intentionally bypass typechecking and proof
/// instrumentation.
pub struct CompiledDisequalityWriter {
    encoding: DisequalityEncoding,
    table: String,
    false_value: Option<Value>,
}

impl CompiledDisequalityWriter {
    /// Bind a writer to the generated table for `sort`.
    ///
    /// The corresponding compiler support must already be installed. A
    /// missing generated table is reported here for EE/OEE or by [`Self::add`]
    /// for NEE/DE.
    pub fn from_installed_support(
        state: &mut FullState<'_, '_>,
        encoding: DisequalityEncoding,
        sort: &str,
    ) -> Result<Self, Error> {
        let table = match encoding {
            DisequalityEncoding::EqualityEmbedding
            | DisequalityEncoding::OptimizedEqualityEmbedding => equality_symbol(sort),
            DisequalityEncoding::NegatedEqualityEmbedding => negated_equality_symbol(sort),
            DisequalityEncoding::DisequalityEdges => disequality_edge_symbol(sort),
        };
        let false_value = match encoding {
            DisequalityEncoding::EqualityEmbedding
            | DisequalityEncoding::OptimizedEqualityEmbedding => {
                Some(state.add(FALSE, RawValues(Vec::new()))?)
            }
            DisequalityEncoding::NegatedEqualityEmbedding
            | DisequalityEncoding::DisequalityEdges => None,
        };
        Ok(Self {
            encoding,
            table,
            false_value,
        })
    }

    /// Insert one compiled disequality assertion into the pending update.
    pub fn add(&self, state: &mut FullState<'_, '_>, lhs: Value, rhs: Value) -> Result<(), Error> {
        match self.encoding {
            DisequalityEncoding::EqualityEmbedding
            | DisequalityEncoding::OptimizedEqualityEmbedding => {
                let equality = state.add(&self.table, RawValues(vec![lhs, rhs]))?;
                state.union(
                    equality,
                    self.false_value
                        .expect("EE writers are initialized with false"),
                )?;
            }
            DisequalityEncoding::NegatedEqualityEmbedding
            | DisequalityEncoding::DisequalityEdges => {
                state.add(&self.table, RawValues(vec![lhs, rhs]))?;
            }
        }
        Ok(())
    }
}

pub(crate) fn add_disequality_support(egraph: &mut egglog::EGraph, encoding: DisequalityEncoding) {
    egraph.parser.add_action_macro(Arc::new(DisequalAction));
    egraph
        .command_macros_mut()
        .register(Arc::new(DisequalityMacro { encoding }));
}

struct DisequalAction;

impl Macro<Vec<Action>> for DisequalAction {
    fn name(&self) -> &str {
        "disequal"
    }

    fn parse(
        &self,
        args: &[Sexp],
        span: Span,
        parser: &mut Parser,
    ) -> Result<Vec<Action>, ParseError> {
        let [lhs, rhs] = args else {
            return Err(ParseError(
                span,
                "usage: (disequal <expr> <expr>)".to_owned(),
            ));
        };
        let lhs = parser.parse_expr(lhs)?;
        let rhs = parser.parse_expr(rhs)?;
        Ok(vec![Action::Expr(
            span.clone(),
            Expr::Call(span, PLACEHOLDER.to_owned(), vec![lhs, rhs]),
        )])
    }
}

struct DisequalityMacro {
    encoding: DisequalityEncoding,
}

impl CommandMacro for DisequalityMacro {
    fn transform(
        &self,
        command: Command,
        symbol_gen: &mut SymbolGen,
        type_info: &TypeInfo,
    ) -> Result<Vec<Command>, Error> {
        match command {
            Command::Rule { mut rule } if contains_disequality(&rule.head) => {
                let mut bindings = Vec::new();
                for fact in type_info.typecheck_facts(symbol_gen, &rule.body)? {
                    fact.visit_vars(&mut |span, var| {
                        if !bindings
                            .iter()
                            .any(|(name, _, _): &(String, Span, ArcSort)| name == &var.name)
                        {
                            bindings.push((var.name.clone(), span.clone(), var.sort.clone()));
                        }
                    });
                }
                let (head, required_sorts) = lower_actions(
                    rule.head,
                    bindings,
                    Context::Full,
                    symbol_gen,
                    type_info,
                    self.encoding,
                )?;
                rule.head = head;
                let mut commands = support_commands(type_info, required_sorts, self.encoding);
                commands.push(Command::Rule { rule });
                Ok(commands)
            }
            Command::Action(action)
                if contains_disequality(&Actions::singleton(action.clone())) =>
            {
                let (mut actions, required_sorts) = lower_actions(
                    Actions::singleton(action),
                    Vec::new(),
                    Context::Full,
                    symbol_gen,
                    type_info,
                    self.encoding,
                )?;
                let mut commands = support_commands(type_info, required_sorts, self.encoding);
                if actions.0.len() == 1 {
                    commands.push(Command::Action(actions.0.remove(0)));
                } else {
                    commands.push(Command::Actions(actions));
                }
                Ok(commands)
            }
            Command::Actions(actions) if contains_disequality(&actions) => {
                let (actions, required_sorts) = lower_actions(
                    actions,
                    Vec::new(),
                    Context::Full,
                    symbol_gen,
                    type_info,
                    self.encoding,
                )?;
                let mut commands = support_commands(type_info, required_sorts, self.encoding);
                commands.push(Command::Actions(actions));
                Ok(commands)
            }
            Command::LetBegin(span, name, actions) if contains_disequality(&actions) => {
                let (actions, required_sorts) = lower_actions(
                    actions,
                    Vec::new(),
                    Context::Full,
                    symbol_gen,
                    type_info,
                    self.encoding,
                )?;
                let mut commands = support_commands(type_info, required_sorts, self.encoding);
                commands.push(Command::LetBegin(span, name, actions));
                Ok(commands)
            }
            command => Ok(vec![command]),
        }
    }
}

fn contains_disequality(actions: &Actions) -> bool {
    actions.0.iter().any(|action| {
        matches!(
            action,
            Action::Expr(_, Expr::Call(_, head, _)) if head == PLACEHOLDER
        )
    })
}

fn lower_actions(
    actions: Actions,
    mut bindings: Vec<(String, Span, ArcSort)>,
    context: Context,
    symbol_gen: &mut SymbolGen,
    type_info: &TypeInfo,
    encoding: DisequalityEncoding,
) -> Result<(Actions, BTreeMap<String, Span>), Error> {
    let mut lowered = Vec::with_capacity(actions.0.len());
    let mut required_sorts = BTreeMap::new();

    for action in actions.0 {
        match action {
            Action::Expr(action_span, Expr::Call(_, head, args)) if head == PLACEHOLDER => {
                let [lhs, rhs] = args.as_slice() else {
                    return Err(Error::DesugarError(
                        action_span,
                        "internal disequal action must have two operands".to_owned(),
                    ));
                };
                let lhs_sort = operand_sort(type_info, symbol_gen, lhs, &bindings, context)?;
                let rhs_sort = operand_sort(type_info, symbol_gen, rhs, &bindings, context)?;
                if lhs_sort.name() != rhs_sort.name() {
                    return Err(TypeError::Mismatch {
                        expr: rhs.clone(),
                        expected: lhs_sort,
                        actual: rhs_sort,
                    }
                    .into());
                }
                if !lhs_sort.is_eq_sort() {
                    return Err(TypeError::NonEqsortUnion(lhs_sort, action_span).into());
                }
                if !type_info.is_sort_unionable(&lhs_sort) {
                    return Err(TypeError::NonUnionableSort(lhs_sort, action_span).into());
                }

                required_sorts
                    .entry(lhs_sort.name().to_owned())
                    .or_insert_with(|| action_span.clone());
                lowered.extend(lower_disequality(
                    action_span,
                    lhs.clone(),
                    rhs.clone(),
                    lhs_sort.name(),
                    encoding,
                ));
            }
            Action::Let(span, name, value) => {
                let sort = type_info.infer_expr_sort(symbol_gen, &value, &bindings, context)?;
                if bindings.iter().any(|(bound, _, _)| bound == &name) {
                    return Err(TypeError::AlreadyDefined(name, span).into());
                }
                bindings.push((name.clone(), span.clone(), sort));
                lowered.push(Action::Let(span, name, value));
            }
            action => lowered.push(action),
        }
    }

    Ok((Actions::new(lowered), required_sorts))
}

/// Select the sort-specific encoding before the generated action is typechecked.
///
/// A variable or declared function has a fixed output sort independent of its
/// operands, so avoid invoking general constraint solving for these common
/// cases. The generated action still goes through normal typechecking and
/// validates the complete operand expressions.
fn operand_sort(
    type_info: &TypeInfo,
    symbol_gen: &mut SymbolGen,
    expr: &Expr,
    bindings: &[(String, Span, ArcSort)],
    context: Context,
) -> Result<ArcSort, TypeError> {
    let declared = match expr {
        Expr::Var(_, name) => bindings
            .iter()
            .find_map(|(bound, _, sort)| (bound == name).then_some(sort))
            .or_else(|| type_info.get_global_sort(name)),
        Expr::Call(_, head, _) if !type_info.is_primitive(head) => type_info
            .get_func_type(head)
            .map(|function| function.output()),
        _ => None,
    };
    match declared {
        Some(sort) => Ok(sort.clone()),
        None => type_info.infer_expr_sort(symbol_gen, expr, bindings, context),
    }
}

fn lower_disequality(
    span: Span,
    lhs: Expr,
    rhs: Expr,
    sort: &str,
    encoding: DisequalityEncoding,
) -> Vec<Action> {
    match encoding {
        DisequalityEncoding::EqualityEmbedding => vec![Action::Union(
            span.clone(),
            call(&span, &equality_symbol(sort), vec![lhs, rhs]),
            call(&span, FALSE, vec![]),
        )],
        DisequalityEncoding::OptimizedEqualityEmbedding => vec![Action::Union(
            span.clone(),
            call(&span, &equality_symbol(sort), vec![lhs, rhs]),
            call(&span, FALSE, vec![]),
        )],
        DisequalityEncoding::NegatedEqualityEmbedding => vec![Action::Expr(
            span.clone(),
            call(&span, &negated_equality_symbol(sort), vec![lhs, rhs]),
        )],
        DisequalityEncoding::DisequalityEdges => {
            let edge = disequality_edge_symbol(sort);
            vec![Action::Expr(
                span.clone(),
                call(&span, &edge, vec![lhs, rhs]),
            )]
        }
    }
}

fn support_commands(
    type_info: &TypeInfo,
    required_sorts: BTreeMap<String, Span>,
    encoding: DisequalityEncoding,
) -> Vec<Command> {
    let Some(base_span) = required_sorts.values().next().cloned() else {
        return Vec::new();
    };
    let mut commands = Vec::new();

    match encoding {
        DisequalityEncoding::EqualityEmbedding
        | DisequalityEncoding::OptimizedEqualityEmbedding => {
            if type_info.get_sort_by_name(TRUTH_SORT).is_none() {
                commands.push(Command::Sort {
                    span: base_span.clone(),
                    name: TRUTH_SORT.to_owned(),
                    presort_and_args: None,
                    uf: None,
                    container_rebuild: None,
                    proof_constructors: None,
                    unionable: true,
                });
                commands.push(constructor(&base_span, TRUE, vec![], TRUTH_SORT));
                commands.push(constructor(&base_span, FALSE, vec![], TRUTH_SORT));
                if encoding == DisequalityEncoding::EqualityEmbedding {
                    commands.push(equality_embedding_contradiction_rule(&base_span));
                }
            }

            let truth_equality = equality_symbol(TRUTH_SORT);
            if type_info.get_func_type(&truth_equality).is_none() {
                commands.extend(equality_support(&base_span, TRUTH_SORT, encoding));
            }

            for (sort, span) in required_sorts {
                let equality = equality_symbol(&sort);
                if type_info.get_func_type(&equality).is_none() && sort != TRUTH_SORT {
                    commands.extend(equality_support(&span, &sort, encoding));
                }
            }
        }
        DisequalityEncoding::NegatedEqualityEmbedding => {
            for (sort, span) in required_sorts {
                let negated_equality = negated_equality_symbol(&sort);
                if type_info.get_func_type(&negated_equality).is_none() {
                    commands.extend(negated_equality_support(&span, &sort));
                }
            }
        }
        DisequalityEncoding::DisequalityEdges => {
            for (sort, span) in required_sorts {
                let edge = disequality_edge_symbol(&sort);
                if type_info.get_func_type(&edge).is_none() {
                    commands.extend(disequality_edge_support(&span, &sort));
                }
            }
        }
    }

    commands
}

fn equality_support(span: &Span, sort: &str, encoding: DisequalityEncoding) -> Vec<Command> {
    match encoding {
        DisequalityEncoding::EqualityEmbedding => equality_embedding_support(span, sort),
        DisequalityEncoding::OptimizedEqualityEmbedding => {
            optimized_equality_embedding_support(span, sort)
        }
        DisequalityEncoding::NegatedEqualityEmbedding | DisequalityEncoding::DisequalityEdges => {
            unreachable!()
        }
    }
}

fn equality_embedding_support(span: &Span, sort: &str) -> Vec<Command> {
    let equality = equality_symbol(sort);
    let suffix = symbol_component(sort);
    let x = Expr::Var(span.clone(), "@disequality-x".to_owned());
    let y = Expr::Var(span.clone(), "@disequality-y".to_owned());
    let eq_xy = call(span, &equality, vec![x.clone(), y.clone()]);
    let eq_yx = call(span, &equality, vec![y.clone(), x.clone()]);
    let eq_xx = call(span, &equality, vec![x.clone(), x.clone()]);
    let eq_yy = call(span, &equality, vec![y.clone(), y.clone()]);
    let true_expr = call(span, TRUE, vec![]);
    let false_expr = call(span, FALSE, vec![]);
    let truth_equality = equality_symbol(TRUTH_SORT);

    vec![
        constructor(span, &equality, vec![sort, sort], TRUTH_SORT),
        rule(
            span,
            format!("@disequality-ee-lift-{suffix}"),
            vec![Fact::Eq(span.clone(), eq_xy.clone(), true_expr.clone())],
            vec![Action::Union(span.clone(), x.clone(), y.clone())],
        ),
        rule(
            span,
            format!("@disequality-ee-symmetry-{suffix}"),
            vec![Fact::Eq(span.clone(), eq_xy.clone(), false_expr.clone())],
            vec![Action::Union(span.clone(), eq_yx, false_expr.clone())],
        ),
        rule(
            span,
            format!("@disequality-ee-double-negation-{suffix}"),
            vec![Fact::Eq(
                span.clone(),
                call(
                    span,
                    &truth_equality,
                    vec![eq_xy.clone(), false_expr.clone()],
                ),
                false_expr.clone(),
            )],
            vec![Action::Union(span.clone(), x.clone(), y.clone())],
        ),
        rule(
            span,
            format!("@disequality-ee-reflexive-left-{suffix}"),
            vec![Fact::Eq(span.clone(), eq_xy.clone(), false_expr.clone())],
            vec![Action::Union(span.clone(), eq_xx, true_expr.clone())],
        ),
        rule(
            span,
            format!("@disequality-ee-reflexive-right-{suffix}"),
            vec![Fact::Eq(span.clone(), eq_xy, false_expr)],
            vec![Action::Union(span.clone(), eq_yy, true_expr)],
        ),
    ]
}

fn optimized_equality_embedding_support(span: &Span, sort: &str) -> Vec<Command> {
    let equality = equality_symbol(sort);
    let suffix = symbol_component(sort);
    let x = Expr::Var(span.clone(), "@disequality-x".to_owned());
    let y = Expr::Var(span.clone(), "@disequality-y".to_owned());
    let eq_xy = call(span, &equality, vec![x.clone(), y.clone()]);
    let false_expr = call(span, FALSE, vec![]);
    let truth_equality = equality_symbol(TRUTH_SORT);

    vec![
        constructor(span, &equality, vec![sort, sort], TRUTH_SORT),
        rule(
            span,
            format!("@disequality-oee-lift-{suffix}"),
            vec![Fact::Eq(
                span.clone(),
                eq_xy.clone(),
                call(span, TRUE, vec![]),
            )],
            vec![Action::Union(span.clone(), x.clone(), y.clone())],
        ),
        rule(
            span,
            format!("@disequality-oee-double-negation-{suffix}"),
            vec![Fact::Eq(
                span.clone(),
                call(
                    span,
                    &truth_equality,
                    vec![eq_xy.clone(), false_expr.clone()],
                ),
                false_expr.clone(),
            )],
            vec![Action::Union(span.clone(), x.clone(), y.clone())],
        ),
        rule(
            span,
            format!("@disequality-oee-contradiction-{suffix}"),
            vec![Fact::Eq(
                span.clone(),
                call(span, &equality, vec![x.clone(), x]),
                false_expr,
            )],
            vec![Action::Panic(
                span.clone(),
                "disequality constraint contradicted".to_owned(),
            )],
        ),
    ]
}

fn negated_equality_support(span: &Span, sort: &str) -> Vec<Command> {
    let negated_equality = negated_equality_symbol(sort);
    let x = Expr::Var(span.clone(), "@disequality-x".to_owned());
    vec![
        constructor(span, &negated_equality, vec![sort, sort], sort),
        rule(
            span,
            format!("@disequality-nee-contradiction-{}", symbol_component(sort)),
            vec![Fact::Fact(call(
                span,
                &negated_equality,
                vec![x.clone(), x],
            ))],
            vec![Action::Panic(
                span.clone(),
                "disequality constraint contradicted".to_owned(),
            )],
        ),
    ]
}

fn disequality_edge_support(span: &Span, sort: &str) -> Vec<Command> {
    let edge = disequality_edge_symbol(sort);
    let x = Expr::Var(span.clone(), "@disequality-x".to_owned());
    let y = Expr::Var(span.clone(), "@disequality-y".to_owned());
    vec![
        Command::Relation {
            span: span.clone(),
            name: edge.clone(),
            inputs: vec![sort.to_owned(), sort.to_owned()],
        },
        rule(
            span,
            format!("@disequality-de-symmetry-{}", symbol_component(sort)),
            vec![Fact::Fact(call(span, &edge, vec![x.clone(), y.clone()]))],
            vec![Action::Expr(
                span.clone(),
                call(span, &edge, vec![y, x.clone()]),
            )],
        ),
        rule(
            span,
            format!("@disequality-de-contradiction-{}", symbol_component(sort)),
            vec![Fact::Fact(call(span, &edge, vec![x.clone(), x]))],
            vec![Action::Panic(
                span.clone(),
                "disequality constraint contradicted".to_owned(),
            )],
        ),
    ]
}

fn equality_embedding_contradiction_rule(span: &Span) -> Command {
    rule(
        span,
        "@disequality-contradiction".to_owned(),
        vec![Fact::Eq(
            span.clone(),
            call(span, TRUE, vec![]),
            call(span, FALSE, vec![]),
        )],
        vec![Action::Panic(
            span.clone(),
            "disequality constraint contradicted".to_owned(),
        )],
    )
}

fn constructor(span: &Span, name: &str, inputs: Vec<&str>, output: &str) -> Command {
    Command::Constructor {
        span: span.clone(),
        name: name.to_owned(),
        schema: Schema {
            input: inputs.into_iter().map(str::to_owned).collect(),
            outputs: vec![output.to_owned()],
        },
        cost: None,
        unextractable: true,
        hidden: true,
        let_binding: false,
        term_constructor: None,
    }
}

fn rule(span: &Span, name: String, body: Vec<Fact>, head: Vec<Action>) -> Command {
    Command::Rule {
        rule: Rule {
            span: span.clone(),
            head: Actions::new(head),
            body,
            name,
            ruleset: String::new(),
            eval_mode: RuleEvalMode::Seminaive,
            no_decomp: false,
            include_subsumed: false,
        },
    }
}

fn call(span: &Span, head: &str, args: Vec<Expr>) -> Expr {
    Expr::Call(span.clone(), head.to_owned(), args)
}

fn equality_symbol(sort: &str) -> String {
    format!("@disequality-eq-{}", symbol_component(sort))
}

fn negated_equality_symbol(sort: &str) -> String {
    format!("@disequality-ne-{}", symbol_component(sort))
}

fn disequality_edge_symbol(sort: &str) -> String {
    format!("@disequality-edge-{}", symbol_component(sort))
}

fn symbol_component(value: &str) -> String {
    let mut encoded = String::with_capacity(value.len() * 2);
    for byte in value.bytes() {
        write!(encoded, "{byte:02x}").expect("writing to a String cannot fail");
    }
    encoded
}

#[cfg(test)]
mod tests {
    use crate::{
        CompiledDisequalityWriter, DisequalityEncoding, new_experimental_egraph,
        new_experimental_egraph_for_proofs_with_disequality_encoding,
        new_experimental_egraph_with_disequality_encoding,
    };
    use egglog::{RawValues, Write};
    use std::path::Path;

    const ENCODINGS: [DisequalityEncoding; 4] = [
        DisequalityEncoding::EqualityEmbedding,
        DisequalityEncoding::OptimizedEqualityEmbedding,
        DisequalityEncoding::NegatedEqualityEmbedding,
        DisequalityEncoding::DisequalityEdges,
    ];

    #[test]
    fn equality_embedding_accepts_consistent_disequality() {
        let mut egraph = new_experimental_egraph();
        egraph
            .parse_and_run_program(
                None,
                r#"
                (datatype Math (A) (B))
                (disequal (A) (B))
                (run 10)
                "#,
            )
            .unwrap();
    }

    #[test]
    fn equality_embedding_rejects_reflexive_disequality() {
        let mut egraph = new_experimental_egraph();
        let error = egraph
            .parse_and_run_program(
                None,
                r#"
                (datatype Math (A))
                (disequal (A) (A))
                (run 10)
                "#,
            )
            .unwrap_err();
        assert!(
            error
                .to_string()
                .contains("disequality constraint contradicted")
        );
    }

    #[test]
    fn equality_embedding_detects_congruence_after_union() {
        let mut egraph = new_experimental_egraph();
        let error = egraph
            .parse_and_run_program(
                None,
                r#"
                (datatype Math (A) (B) (F Math))
                (disequal (F (A)) (F (B)))
                (union (A) (B))
                (run 10)
                "#,
            )
            .unwrap_err();
        assert!(
            error
                .to_string()
                .contains("disequality constraint contradicted")
        );
    }

    #[test]
    fn compiled_writer_matches_source_for_every_encoding() {
        for encoding in ENCODINGS {
            let setup = r#"
                (datatype Math (A) (B) (C) (F Math))
                (disequal (A) (B))
            "#;
            let mut source = new_experimental_egraph_with_disequality_encoding(encoding);
            source.parse_and_run_program(None, setup).unwrap();
            source
                .parse_and_run_program(None, "(disequal (F (A)) (F (C))) (run 10)")
                .unwrap();

            let mut compiled = new_experimental_egraph_with_disequality_encoding(encoding);
            compiled.parse_and_run_program(None, setup).unwrap();
            compiled
                .update(|mut state| {
                    let a = state.add("A", RawValues(Vec::new()))?;
                    let c = state.add("C", RawValues(Vec::new()))?;
                    let fa = state.add("F", RawValues(vec![a]))?;
                    let fc = state.add("F", RawValues(vec![c]))?;
                    let writer = CompiledDisequalityWriter::from_installed_support(
                        &mut state, encoding, "Math",
                    )?;
                    writer.add(&mut state, fa, fc)
                })
                .unwrap();
            compiled.parse_and_run_program(None, "(run 10)").unwrap();
            assert_eq!(
                compiled.num_tuples(),
                source.num_tuples(),
                "{encoding} bulk and source paths produced different databases"
            );

            for (mode, egraph) in [("source", &mut source), ("compiled", &mut compiled)] {
                let error = egraph
                    .parse_and_run_program(None, "(union (A) (C)) (run 10)")
                    .unwrap_err();
                assert!(
                    error
                        .to_string()
                        .contains("disequality constraint contradicted"),
                    "{encoding} {mode} path did not detect congruence: {error}"
                );
            }
        }
    }

    #[test]
    fn equality_embedding_works_in_rule_actions() {
        let mut egraph = new_experimental_egraph();
        let error = egraph
            .parse_and_run_program(
                None,
                r#"
                (datatype Math (A) (B))
                (relation apart (Math Math))
                (apart (A) (B))
                (rule ((apart x y)) ((disequal x y)))
                (run 10)
                (union (A) (B))
                (run 10)
                "#,
            )
            .unwrap_err();
        assert!(
            error
                .to_string()
                .contains("disequality constraint contradicted")
        );
    }

    #[test]
    fn disequality_requires_matching_unionable_sorts() {
        let mut egraph = new_experimental_egraph();
        let mismatch = egraph
            .parse_and_run_program(
                None,
                r#"
                (datatype Left (L))
                (datatype Right (R))
                (disequal (L) (R))
                "#,
            )
            .unwrap_err();
        assert!(mismatch.to_string().contains("to have type Left"));

        let mut egraph = new_experimental_egraph();
        let primitive = egraph
            .parse_and_run_program(None, "(disequal 1 2)")
            .unwrap_err();
        assert!(
            primitive
                .to_string()
                .contains("Cannot union values of sort i64")
        );

        let mut egraph = new_experimental_egraph();
        let malformed = egraph
            .parse_and_run_program(
                None,
                r#"
                (datatype Math (A) (F Math))
                (disequal (F) (A))
                "#,
            )
            .unwrap_err();
        assert!(
            malformed.to_string().contains("Arity mismatch"),
            "unexpected malformed-operand error: {malformed}"
        );
    }

    #[test]
    fn all_encodings_detect_direct_and_congruence_contradictions() {
        for encoding in ENCODINGS {
            let mut egraph = new_experimental_egraph_with_disequality_encoding(encoding);
            egraph
                .parse_and_run_program(
                    None,
                    r#"
                    (datatype Math (A) (B) (F Math))
                    (disequal (A) (B))
                    (run 10)
                    "#,
                )
                .unwrap_or_else(|error| {
                    panic!("{encoding:?} rejected a consistent graph: {error}")
                });

            let mut egraph = new_experimental_egraph_with_disequality_encoding(encoding);
            let direct = egraph
                .parse_and_run_program(
                    None,
                    r#"
                    (datatype Math (A))
                    (disequal (A) (A))
                    (run 10)
                    "#,
                )
                .expect_err("a reflexive disequality must be contradictory");
            assert!(
                direct
                    .to_string()
                    .contains("disequality constraint contradicted"),
                "unexpected {encoding:?} error: {direct}"
            );

            let mut egraph = new_experimental_egraph_with_disequality_encoding(encoding);
            let congruence = egraph
                .parse_and_run_program(
                    None,
                    r#"
                    (datatype Math (A) (B) (F Math))
                    (disequal (F (A)) (F (B)))
                    (union (A) (B))
                    (run 10)
                    "#,
                )
                .expect_err("congruence must expose the disequality self-loop");
            assert!(
                congruence
                    .to_string()
                    .contains("disequality constraint contradicted"),
                "unexpected {encoding:?} error: {congruence}"
            );
        }
    }

    #[test]
    fn all_encodings_support_rule_and_action_local_bindings() {
        let program = r#"
            (datatype Math (A) (B) (F Math))
            (relation apart (Math Math))
            (apart (A) (B))
            (rule ((apart x y))
                  ((let fy (F y))
                   (disequal (F x) fy)))
            (begin
              (let left (A))
              (disequal left (B)))
            (run 10)
            (union (A) (B))
            (fail (run 10))
        "#;

        for encoding in ENCODINGS {
            let mut egraph = new_experimental_egraph_with_disequality_encoding(encoding);
            egraph
                .parse_and_run_program(None, program)
                .unwrap_or_else(|error| panic!("{encoding:?} failed local bindings: {error}"));
        }
    }

    #[test]
    fn all_encodings_generate_independent_support_for_each_sort() {
        let program = r#"
            (datatype Left (L0) (L1))
            (datatype Right (R0) (R1))
            (disequal (L0) (L1))
            (disequal (R0) (R1))
            (run 10)
            (union (L0) (L1))
            (fail (run 10))
        "#;

        for encoding in ENCODINGS {
            let mut egraph = new_experimental_egraph_with_disequality_encoding(encoding);
            egraph
                .parse_and_run_program(None, program)
                .unwrap_or_else(|error| panic!("{encoding:?} failed multiple sorts: {error}"));
        }
    }

    #[test]
    fn all_encodings_regenerate_support_after_pop() {
        let program = r#"
            (datatype Math (A) (B))
            (push)
            (disequal (A) (B))
            (pop)
            (disequal (A) (B))
            (run 10)
        "#;

        for encoding in ENCODINGS {
            let mut egraph = new_experimental_egraph_with_disequality_encoding(encoding);
            egraph
                .parse_and_run_program(None, program)
                .unwrap_or_else(|error| panic!("{encoding:?} failed push/pop: {error}"));
        }
    }

    #[test]
    fn disequality_edges_are_materialized_symmetrically() {
        let mut egraph = new_experimental_egraph_with_disequality_encoding(
            DisequalityEncoding::DisequalityEdges,
        );
        egraph
            .parse_and_run_program(
                None,
                r#"
                (datatype Math (A) (B))
                (disequal (A) (B))
                (run 10)
                "#,
            )
            .unwrap();

        assert_eq!(egraph.get_size(&super::disequality_edge_symbol("Math")), 2);
    }

    #[test]
    fn all_encodings_run_paper_and_artifact_ports() {
        let fixture_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/disequality");
        for fixture in [
            "paper-figure-2.egg",
            "artifact-euf-example.egg",
            "artifact-propel-example.egg",
            "artifact-parameter-shape.egg",
        ] {
            let program = std::fs::read_to_string(fixture_dir.join(fixture)).unwrap();
            for encoding in ENCODINGS {
                let mut egraph = new_experimental_egraph_with_disequality_encoding(encoding);
                egraph
                    .parse_and_run_program(Some(fixture.to_owned()), &program)
                    .unwrap_or_else(|error| panic!("{encoding:?} failed {fixture}: {error}"));
            }
        }
    }

    #[test]
    fn all_encodings_compose_with_term_and_proof_modes() {
        let program = r#"
            (datatype Math (A) (B) (C) (F Math))
            (disequal (F (A)) (F (C)))
            (union (A) (B))
            (run 3)
            (check (= (A) (B)))
            (union (B) (C))
            (fail (run 3))
        "#;

        for encoding in ENCODINGS {
            let mut term_egraph =
                new_experimental_egraph_for_proofs_with_disequality_encoding(encoding)
                    .with_term_encoding_enabled();
            term_egraph
                .parse_and_run_program(None, program)
                .unwrap_or_else(|error| panic!("{encoding:?} failed term encoding: {error}"));

            let mut proof_egraph =
                new_experimental_egraph_for_proofs_with_disequality_encoding(encoding)
                    .with_proofs_enabled()
                    .with_proof_testing();
            proof_egraph
                .parse_and_run_program(None, program)
                .unwrap_or_else(|error| panic!("{encoding:?} failed proof testing: {error}"));
        }
    }
}
